### ISSUE TITLE
希望以后能支持KSP

### ISSUE THREAD

**Issue by tanranran** [HuolalaTech/hll-wp-therouter-android#1]
如题，KAPT有点慢

**Comment by kymjs** [comment]
其实已经开发了，只是由于`ksp`还在`alpha`，跟协程一样，不确定将来会不会又发生`API`大变动。所以，我们暂时没有在生产环境使用，等`ksp`正式版发布以后，会第一时间开源。

**Comment by RicardoJiang** [comment]
同求，ksp不是已经发布稳定版本了吗？

**Comment by kymjs** [comment]
#22
