### ISSUE TITLE
KSP编译后运行失败

### ISSUE THREAD

**Issue by l511809934** [HuolalaTech/hll-wp-therouter-android#101]
<img width="860" alt="91b21ef04f1f29c1faadb66c8f220d5" src="https://github.com/HuolalaTech/hll-wp-therouter-android/assets/18045648/4ea58028-8f6a-4337-bda2-767ff80df397">
如图所示
theroute='1.1.4'
agp='7.3.0'
as为最新
使用kapt编译后运行一切正常

**Comment by whoislxy** [comment]
Hi guys，I have the same problem as you！

**Comment by kymjs** [comment]
请更新版本至 `1.2.0-rc4`后再次尝试
