### ISSUE TITLE
报错的时候不打印具体错误日志

### ISSUE THREAD

**Issue by linqip** [HuolalaTech/hll-wp-therouter-android#103]
使用 kotlin Autowired 传递 Parcelable 对象类型参数时，对象内某个不可为空的字段为空了 。获取参数的时候会导致整个对象都为空，即时这个参数没使用也是。

此时日志不会体现哪个字段为空导致整个整个对象为空。

**Comment by linqip** [comment]
.withObject() 传参正常，.withParcelable()会导致整个对象都为空

**Comment by kymjs** [comment]
麻烦提供一下具体的代码场景

**Comment by linqip** [comment]
您的邮件已经收到了，我看到后会第一时间回复的。 谢谢 ！

**Comment by linqip** [comment]
打开页面
TheRouter.build(RouterActivityPath.MY_TIMES_PACKAGES_DETAIL_ACTIVITY)
                        .withParcelable("myPackageBean", data)
                        .navigation(mActivity)
数据类型
@Parcelize
data class MyPackageBean(
    val carNo: String?,
    val packageCode: String,
    val packageInstanceId: String,
    val packageName: String,
    val rightEndTime: String,
    val rightInfo: List<RightInfo>,
    val rightStartTime: String,
    val saleOriginalPrice: Double,
    val status: Int,
    val swapPowerAmount: String
) : Parcelable
内部类
@Parcelize
data class RightInfo(
    val carNo: String?,
    val leaveOfNum: Int,
    val packageInstanceId: String,（服务端这个字段返回空)
    val phone: String,
    val shiftEnd: String?,
    val shiftStart: String?,
    val unUseOfNum: Int,
    val usedOfNum: Int,
    val userId: String,
    val userName: String
) : Parcelable
接收
 @Autowired(name = "myPackageBean")
    lateinit var myPackageBean: MyPackageBean

TheRouter.inject(this)

**Comment by linqip** [comment]
由于公司网络限制不能截图、智能贴关键代码，版本号 1,1,3

**Comment by kymjs** [comment]
这个跟`TheRouter`框架没关系，`kotlin`不允许非空字段赋值为`null`
