### ISSUE TITLE
AutoWrite 的 bug

### ISSUE THREAD

**Issue by xiaolei123** [HuolalaTech/hll-wp-therouter-android#104]
我有两个类：
interface ICar
class RedCar : ICar,Parcelable

在A页面进行路由，注入 withParcelable("car",new RedCar())

在B页面接收：
class BActivity{
@AutoWrite late val car : ICar
}

这时候，我获取不到我的值。我查看源码，是在处理注入的时候，没有考虑超类的问题。

**Comment by kymjs** [comment]
是的，场景比较少，暂时不考虑支持这种情况
