### ISSUE TITLE
gradle8 gradle.kts 编译失败

### ISSUE THREAD

**Issue by gengzhaohe** [HuolalaTech/hll-wp-therouter-android#106]
1 problem was found storing the configuration cache.
- Task `:app:debugTheRouterGetAllClasses` of type `com.therouter.plugin.agp8.TheRouterGetAllClassesTask`: invocation of 'Task.project' at execution time is unsupported.
  See https://docs.gradle.org/8.0/userguide/configuration_cache.html#config_cache:requirements:use_project_during_execution

See the complete report at file:///Users/huajiao/myprj/ata/ata-android/build/reports/configuration-cache/cbngny7vmeq10ks1esuvg880b/3r0xhnmj9r540pmcrjvjuvqea/configuration-cache-report.html
> Invocation of 'Task.project' by task ':app:debugTheRouterGetAllClasses' at execution time is unsupported.

project-> build.gradle.kts
plugins {
    id("com.android.application") version "8.1.0" apply false
    id("org.jetbrains.kotlin.android") version "1.8.10" apply false
    id("com.android.library") version "8.1.0" apply false
    id("com.google.devtools.ksp") version "1.8.10-1.0.9" apply false
    id("com.google.dagger.hilt.android") version "2.47" apply false
    id("cn.therouter.agp8") version "1.2.0-rc1" apply false
}

app -> build.gradle.kts
plugins {
    id("com.google.devtools.ksp")
    id("com.android.application")
    id("org.jetbrains.kotlin.android")
    kotlin("kapt")
    id("com.google.dagger.hilt.android")
    id("therouter")
}

**Comment by kymjs** [comment]
`1.2.0-rc3`，已修复

**Comment by gengzhaohe** [comment]
更新到 1.2.0-rc5 还是不行

* Exception is:
org.gradle.configurationcache.ConfigurationCacheProblemsException: Configuration cache problems found in this build.

1 problem was found storing the configuration cache.
- Task `:app:debugTheRouterGetAllClasses` of type `com.therouter.plugin.agp8.TheRouterGetAllClassesTask`: invocation of 'Task.project' at execution time is unsupported.
  See https://docs.gradle.org/8.0/userguide/configuration_cache.html#config_cache:requirements:use_project_during_execution

// Top-level build file where you can add configuration options common to all sub-projects/modules.
plugins {
    id("com.android.application") version "8.0.0" apply false
    id("org.jetbrains.kotlin.android") version "1.8.10" apply false
    id("com.android.library") version "8.0.0" apply false
    id("com.google.devtools.ksp") version "1.8.10-1.0.9" apply false
    id("com.google.dagger.hilt.android") version "2.47" apply false
    id("cn.therouter.agp8") version "1.2.0-rc5" apply false
}
