### ISSUE TITLE
FlowTask加dependsOn如何支持多进程

### ISSUE THREAD

**Issue by aqyana** [HuolalaTech/hll-wp-therouter-android#107]

**Comment by aqyana** [comment]
主进程在隐私协议后初始化了另一个进程，但是加上dependsOn后，另一个进程没有走想要的初始化操作

**Comment by aqyana** [comment]
@FlowTask(taskName = "initH5Container", dependsOn = "afterAgreePrivacy", async = true)
fun initH5Container(context: Context) {}

**Comment by kymjs** [comment]
`FlowTask`暂时不支持跨进程通信，这个特性预计在`1.2.2`版本支持
