### ISSUE TITLE
生成的routeMap.json一直为空

### ISSUE THREAD

**Issue by mtzqc** [HuolalaTech/hll-wp-therouter-android#109]
可以生成routeMap.json文件，但是json文件为空数组，之前都是正常的，以为是今天修改了配置，回退之前的正常的git版本还是一样。会正常生成ServiceProvider__TheRouter___xxxx文件，把上一个版本的routeMap.json复制进去可以正常运行，但是新添加的@Route不会自动添加到路由表，版本1.2.0-rc1，1.2.0-rc2都是这样

**Comment by kymjs** [comment]
用的是 KSP 还是 KAPT

**Comment by mtzqc** [comment]
id "com.google.devtools.ksp" version '1.8.20-1.0.11' apply false

**Comment by mtzqc** [comment]
jdk也切换成非android studio自带的17，控制台输出一切正常，就是生成的路由为空
![image](https://github.com/HuolalaTech/hll-wp-therouter-android/assets/29159362/3ddecd98-bfc3-4baf-a0d1-9ea43257322e)
![image](https://github.com/HuolalaTech/hll-wp-therouter-android/assets/29159362/85463c28-4ebc-4df8-96ea-60c131956c6e)
![image](https://github.com/HuolalaTech/hll-wp-therouter-android/assets/29159362/3538a50b-eb5f-4769-835f-e33e68b85f96)

**Comment by Tan-Tshunglee** [comment]
TheRouter编译插件：cn.therouter:plugin:1.2.0-rc1
当前编译 JDK Version 为::11.0.15
本次是增量编译::false
ksp 版本1.9.10-1.0.13
也有这个问题

**Comment by Tan-Tshunglee** [comment]
app/src/main/assets/therouter/routerMap.json
这个文件倒是有更新，但是编译后打包的apk里面没有这个文件

**Comment by kymjs** [comment]
`1.2.0-rc3`已修复

**Comment by wangkai147** [comment]
![image](https://github.com/HuolalaTech/hll-wp-therouter-android/assets/51751979/838535dd-d164-48b0-bc43-362b2be7c532)
希望后续版本号尽量统一一下

**Comment by kymjs** [comment]
已更新，可从`mavenCentral`官网地址查阅版本号，镜像仓库可能会延迟同步
https://repo.maven.apache.org/maven2/cn/therouter/

**Comment by mtzqc** [comment]
可以正常生成路由了

**Comment by kymjs** [comment]
`1.2.0-rc4`发现`ActionManager`有线程安全问题，请使用`1.2.0-rc5`
