### ISSUE TITLE
注意跟Sophix热修复一起使用出现的问题

### ISSUE THREAD

**Issue by jkbwfi** [HuolalaTech/hll-wp-therouter-android#110]
使用的阿里的Sophix 版本：com.aliyun.ams:alicloud-android-hotfix:3.3.8
therouter 版本 1.1.4

如果开启theRouterUseAutoInit =true 支持多进程，并且当前的开发版本(0.0.1)发布了热修复 patch, 且基于该版本(0.0.1)继续开发，但是 commit 不同了，导致 mapping 文件不同，Sophix子进程无法加载到对应的 class 会导致子进程异常（但不会崩溃）,therouter 的 router_map 无法addItem
导致路由为空无法跳转。 
解决：发布 patch 后及时切换新版本号。

**Comment by kymjs** [comment]
`theRouterUseAutoInit = true`表示不使用自动初始化。
TheRouter 默认只在主进程自动初始化，如果想在子进程也初始化，需要置为`false`并手动初始化。
