### ISSUE TITLE
拦截器、全局降级落地页这块实现好像没Arouter那样方便

### ISSUE THREAD

**Issue by LiWeiQiangAndroid** [HuolalaTech/hll-wp-therouter-android#111]
迁移起来有点麻烦

/**
 *不带参数跳转使用 bundle
 * @param path
 */
inline fun goto(path: String) {
    ARouter.getInstance().build(path).greenChannel().navigation()
}

/**
 * Arouter通用跳转，绿色通道
 */
inline fun goto(path: String, func: Postcard.() -> Unit) = run {
    ARouter.getInstance().build(path).greenChannel().apply {
        this.func()
    }.navigation()
}

/**
 * 带登录拦截器 跳转
 */
inline fun gotoNeedLogin(path: String) {
    ARouter.getInstance().build(path).navigation(AppUtils.application, LoginNavigationCallbackImpl())
}

/**
 * 带登录拦截器跳转
 */
fun gotoNeedLogin(path: String, func: Postcard.() -> Unit) = run {
    ARouter.getInstance().build(path).apply {
        this.func()
    }.navigation(AppUtils.application, LoginNavigationCallbackImpl())
}

//拦截器
class LoginNavigationCallbackImpl : NavigationCallback {

    /**
     * 找到了
     */
    override fun onFound(postcard: Postcard?) {

    }

    /**
     * 找不到了
     */
    override fun onLost(postcard: Postcard?) {

    }

    /**
     * 跳转成功了
     */
    override fun onArrival(postcard: Postcard?) {

    }

    override fun onInterrupt(postcard: Postcard?) {
        // 被登录拦截了下来了
        // 需要调转到登录页面，把参数跟被登录拦截下来的路径传递给登录页面，登录成功后再进行跳转被拦截的页面
        val path = postcard?.path
        val bundle = postcard?.extras
        //获取登录路由服务
        val loginService = ARouter.getInstance().build(RoutePath.Login.SERVICE_LOGIN).navigation() as ILoginService?
        loginService?.userLogin(path, bundle)
    }
}

@Interceptor(name = "login", priority = 8)
class LoginInterceptorImpl : IInterceptor {
    override fun init(context: Context?) {
        //此方法只会走一次
        LogUtil.e("登录拦截器初始化成功")
    }

    override fun process(postcard: Postcard?, callback: InterceptorCallback?) {
        val path = postcard?.path
        if (isLogin()) { // 如果已经登录不拦截
            callback?.onContinue(postcard)
        } else {
            when (path) {
                // 不需要登录的直接进入这个页面
                RoutePath.Main.MAIN_HOME,
                RoutePath.Me.ACTIVITY_HOST,
                RoutePath.Login.PAGE_GLOBAL_LOST,
                RoutePath.Login.PAGE_LOGIN_MSG ->
                    callback?.onContinue(postcard)

                else -> {
                    // 需要登录的直接拦截下来
                    callback?.onInterrupt(null)
                }
            }
        }
    }
}

//全局降级
@Route(path = RoutePath.DegradeService)
class DegradeServiceImpl : DegradeService {
    override fun init(context: Context?) {
        LogUtil.e("路由降级服务初始化成功")
    }

    override fun onLost(context: Context?, postcard: Postcard?) {
        //跳转错误页
        goto(RoutePath.Login.PAGE_GLOBAL_LOST)
    }
}

**Comment by kymjs** [comment]
`greenChannel`使用场景较小众，暂不考虑。拦截器都有相关替代，请查看文档。
