### ISSUE TITLE
Expected stack map table for method with non-linear control flow

### ISSUE THREAD

**Issue by weinierfei** [HuolalaTech/hll-wp-therouter-android#118]
![image](https://github.com/HuolalaTech/hll-wp-therouter-android/assets/11873816/1e10c2ec-7d02-4da5-960f-cbc91efda158)
最新版本插件，编译的时候会产生大量的警告。
`AGPBI: {"kind":"warning","text":"Expected stack map table for method with non-linear control flow.","sources":[{"file":"/Users/pc/StudioProjects/fyzx/AndroidApp/app/build/intermediates/classes/debug/ALL/debugTheRouterGetAllClasses/classes.jar"}],"tool":"D8"}`

该警告耗时，随便改个类，编译一下两分钟，请问这个怎么排查一下？

**Comment by AversonCoder** [comment]
+1

**Comment by kymjs** [comment]
Gradle 7.x 的警告，目的是提示应用内使用了字节码技术，可能修改编译产物，属正常情况。
