### ISSUE TITLE
从ARouter一键迁徙过来，报错了，

### ISSUE THREAD

**Issue by diandian8801** [HuolalaTech/hll-wp-therouter-android#120]
报错内容提示：按照提示，下载了插件，一键迁。 

目前使用的版本：
根目录：classpath cn.therouter:plugin:1.1.4

各个组件：api cn.therouter:router:1.1.4
kapt cn.therouter:apt:1.1.4
以及： apply plugin: 'therouter'

一顿操作猛如虎，sync一下，就懵了。

`Could not find com.android.tools.build:gradle:3.6.3.
Searched in the following locations:
  - https://plugins.gradle.org/m2/com/android/tools/build/gradle/3.6.3/gradle-3.6.3.pom
If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
Required by:
    project :app > cn.therouter:cn.therouter.gradle.plugin:1.2.0-rc6
Add google Maven repository and sync project
Open File
`

**Comment by kymjs** [comment]
> Add google Maven repository and sync project
IDE都已经把处理方式告诉你了
