### ISSUE TITLE
API 'android.registerTransform' is removed  at gradle 8.x

### ISSUE THREAD

**Issue by huasheng0401** [HuolalaTech/hll-wp-therouter-android#121]
**when i use  classpath "cn.therouter:plugin:1.1.4" , an error occurred :** 
<img width="443" alt="remove" src="https://github.com/HuolalaTech/hll-wp-therouter-android/assets/6093568/89718a3a-a5d0-47af-914d-65a86a79b08e">
<img width="634" alt="remove_info" src="https://github.com/HuolalaTech/hll-wp-therouter-android/assets/6093568/41d27465-3fae-4613-9368-2c9fecc87dc8">

> 

**when i use  classpath 'cn.therouter.agp8:plugin:1.2.0-rc1' , an error occurred :** 
<img width="716" alt="not_found" src="https://github.com/HuolalaTech/hll-wp-therouter-android/assets/6093568/58e79350-b279-4f85-a222-e851b3ee2a73">

**Comment by kymjs** [comment]
https://therouter.cn/docs/2022/11/23/01

**Comment by kymjs** [comment]
#97
