### ISSUE TITLE
模块初始化@FlowTask(taskName = 在 Kotlin 中不执行

### ISSUE THREAD

**Issue by hlovingness** [HuolalaTech/hll-wp-therouter-android#123]
版本是最新版
以下方式不执行
<img width="941" alt="image" src="https://github.com/HuolalaTech/hll-wp-therouter-android/assets/16331459/b051c332-60ea-41fc-b26c-f965db156231">

然后换成 top level 函数也不行
<img width="940" alt="image" src="https://github.com/HuolalaTech/hll-wp-therouter-android/assets/16331459/d38097d0-06ac-4070-b8c7-5dafc3eb3fd9">

**Comment by kymjs** [comment]
代码没有问题，需要进一步配合排查请查看 #57 ，或提供apk

**Comment by kymjs** [comment]
可尝试`1.2.0-rc8`版本
