### ISSUE TITLE
怎样通过路径获取类？

### ISSUE THREAD

**Issue by LiWeiQiangAndroid** [HuolalaTech/hll-wp-therouter-android#124]
像ARouter那样
LogisticsCenter.completion(postcard);
 Class aClass = postcard.getDestination();

TheRouter如何获取

**Comment by kymjs** [comment]
https://therouter.cn/docs/2022/08/27/01

**Comment by LiWeiQiangAndroid** [comment]
一键迁移 可以做到？

/**
     * 获取指定指定Activity.class
     *
     * @param url
     */
    public static Class getActivityClass(String url) {
        Postcard postcard = ARouter.getInstance().build(url);
        LogisticsCenter.completion(postcard);
        Class aClass = postcard.getDestination();
        return aClass;
    }

**Comment by kymjs** [comment]
> https://therouter.cn/docs/2022/08/27/01

请先查看官网文档

**Comment by LiWeiQiangAndroid** [comment]
文档的实现过于复杂，按文档还得写多余的接口，没那么方便吧，新增一个调用就需要新增一个接口实现

**Comment by kymjs** [comment]
ActionManager
