### ISSUE TITLE
打包编译失败

### ISSUE THREAD

**Issue by vistar1986** [HuolalaTech/hll-wp-therouter-android#126]
![1699320617073](https://github.com/HuolalaTech/hll-wp-therouter-android/assets/11677770/e6f2c4bb-13a2-4134-bc1b-e10897e329bb)

打包编译失败报错，但是debug是可以编译成功的，没有进行混淆，R8的fullmode也关闭了

**Comment by kymjs** [comment]
参考官网排错文档检查，或登记应用获取优先支持   
[https://therouter.cn/docs/2023/07/21/01](https://therouter.cn/docs/2023/07/21/01)
