### ISSUE TITLE
打印了编译错误信

### ISSUE THREAD

**Issue by lq7y7-go** [HuolalaTech/hll-wp-therouter-android#127]
![截屏2023-11-10 17 04 19](https://github.com/HuolalaTech/hll-wp-therouter-android/assets/55487719/455a418b-dcac-4b4e-b057-6c868a98cc16)
![截屏2023-11-10 17 04 02](https://github.com/HuolalaTech/hll-wp-therouter-android/assets/55487719/f9163eb2-34d5-45c7-8e34-73b443d2fa0d)
虽然不影响编译，但是看着好难受，能解决下么？

**Comment by kymjs** [comment]
`1.2.2-rc1`已经修复
