### ISSUE TITLE
agp8.0 build failed java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by ssj4429108** [HuolalaTech/hll-wp-therouter-android#130]
plugin com.growingio.android.saas 和 therouter 同时存在会出现问题
![image](https://github.com/HuolalaTech/hll-wp-therouter-android/assets/10632084/17bfb3a4-d89d-4b92-861a-259c8a79ade4)

能否支持忽略或者白名单配置？

**Comment by ssj4429108** [comment]
基调听云agp 8.0兼容问题

**Comment by dengshiwei** [comment]
mark，这个问题该如何规避呢？
