### ISSUE TITLE
编译发生时Attempted to serialize java.lang.Class: java.net.URI. Forgot to register a type adapter?

### ISSUE THREAD

**Issue by mozhimen** [HuolalaTech/hll-wp-therouter-android#134]
- 问题版本 1.2.1

- 问题描述
>Attempted to serialize java.lang.Class: java.net.URI. Forgot to register a type adapter?

![image](https://github.com/HuolalaTech/hll-wp-therouter-android/assets/58215586/d7908dbb-4b3c-4ed5-bc86-1a4250035c0d)
- 问题复现方式

注解@Route(path="/third?type=mod")在

![image](https://github.com/HuolalaTech/hll-wp-therouter-android/assets/58215586/2baca5b4-80bb-42e4-8c88-67b9540700e5)

- 注解异常处理打印RouteItem和正常RouteItem对比

![image](https://github.com/HuolalaTech/hll-wp-therouter-android/assets/58215586/1f735a14-3b9f-4fb5-b1bf-4658e44013f7)

![image](https://github.com/HuolalaTech/hll-wp-therouter-android/assets/58215586/5f725715-10ea-4943-bbb7-85b39b6eac37)

- gson序列化问题所在位置

![微信图片_20231226222421](https://github.com/HuolalaTech/hll-wp-therouter-android/assets/58215586/7c1c931a-ace6-41ee-a725-017456edef9e)

**Comment by kymjs** [comment]
路由的path定义时不能带参数，如需要向落地页传参，请使用运行时代码传参。如果需要声明默认参数，可在注解的params字段传递。    
https://therouter.cn/docs/2022/08/28/01
