### ISSUE TITLE
目标页面接收object出现编译失败

### ISSUE THREAD

**Issue by yihuajia** [HuolalaTech/hll-wp-therouter-android#138]
therouter版本:1.2.2-rc4
agp版本：8.1.1

页面AFragment，对应package name为:com.a.b.setting
在AFragment中
@Autowired(name = "test")
lateinit var test: Test 
编译失败

在生成的TheRouter__Autowired类autowiredInject方法中，判断参数obj的时候，AFragment的包名变成了com.a.setting，导致无法找到AFragment。而AFragment实际的包名为:com.a.b.setting。只要注释掉接收对象便能正常编译通过。

**Comment by ruoxuanFu** [comment]
1.2.2-rc4和1.2.2-rc5
当前编译 JDK Version 为::17.0.9
GradleVersion::8.4

Java代码
目标页面接收Parcelable对象时，能接收到对象，但是对象中变量的值接收不到

**Comment by yihuajia** [comment]
> 重复的时候，KSP会识别错误，可以先修改类名或包名。

好的。暂时通过string的方式处理了

**Comment by kymjs** [comment]
> 1.2.2-rc4和1.2.2-rc5 当前编译 JDK Version 为::17.0.9 GradleVersion::8.4
> 
> Java代码 目标页面接收Parcelable对象时，能接收到对象，但是对象中变量的值接收不到

序列化出问题了，写个demo测试你的对象是不是可以正常序列化，`Parcelable`的实现对象，包含的变量也必须是可以`Parcelable`的

**Comment by kymjs** [comment]
已修复   
https://github.com/HuolalaTech/hll-wp-therouter-android/releases/tag/1.2.2-rc7

**Comment by ruoxuanFu** [comment]
> > 1.2.2-rc4和1.2.2-rc5 当前编译 JDK Version 为::17.0.9 GradleVersion::8.4
> > Java代码 目标页面接收Parcelable对象时，能接收到对象，但是对象中变量的值接收不到
> 
> 序列化出问题了，写个demo测试你的对象是不是可以正常序列化，`Parcelable`的实现对象，包含的变量也必须是可以`Parcelable`的

序列化应该没问题，1.2.2-rc3版本和之前版本都是可以成功接收的，1.2.2-rc3之后版本都不行

**Comment by ruoxuanFu** [comment]
> > 1.2.2-rc4和1.2.2-rc5 当前编译 JDK Version 为::17.0.9 GradleVersion::8.4
> > Java代码 目标页面接收Parcelable对象时，能接收到对象，但是对象中变量的值接收不到
> 
> 序列化出问题了，写个demo测试你的对象是不是可以正常序列化，`Parcelable`的实现对象，包含的变量也必须是可以`Parcelable`的

这是我用Intent传，可以正常接收到
![微信截图_20240223135130](https://github.com/HuolalaTech/hll-wp-therouter-android/assets/23335430/8897730c-7cf9-4356-b45c-5b83d2d805f9)

用TheRouter的withParcelable，接收不到
![微信截图_20240223135514](https://github.com/HuolalaTech/hll-wp-therouter-android/assets/23335430/6aa83de4-5dd8-4506-bb8d-37510e918a1f)
![微信截图_20240223135703](https://github.com/HuolalaTech/hll-wp-therouter-android/assets/23335430/c66579ce-efa7-493c-aa5e-2426a8e26438)


版本：
欢迎使用 TheRouter 编译插件：cn.therouter:plugin-agp8:1.2.2-rc6
当前编译 JDK Version 为::17.0.7
GradleVersion::8.4

**Comment by kymjs** [comment]
@ruoxuanFu  试一下rc4和rc5有没有问题呢

**Comment by ruoxuanFu** [comment]
> @ruoxuanFu 试一下rc4、rc5、rc8有没有问题呢

rc4，5之前就试过，不行

rc8也不行
![微信截图_20240223144441](https://github.com/HuolalaTech/hll-wp-therouter-android/assets/23335430/d68a24d3-b93d-4849-8338-9b74daac5751)
