### ISSUE TITLE
请问如何解决一次跳转多个Activity,类似原生startActivities?

### ISSUE THREAD

**Issue by Jeffery336699** [HuolalaTech/hll-wp-therouter-android#139]
请问如果是一个这样的需求 , A页面-->C页面 , 在中间需要插入个B页面 ; 方便C返回的时候直接显示的是B页面 , 再返回才是A页面 .
请问大佬有没有暴露相关的API服务 , 希望能得到解答 , 万分感谢❤~~

**Comment by kymjs** [comment]
写两遍 
`TheRouter.build(xxx).navigation()`
