### ISSUE TITLE
没有withParcelableArrayList

### ISSUE THREAD

**Issue by goIntoAction** [HuolalaTech/hll-wp-therouter-android#14]
Bundle本身就支持，加上很简单，请问后面会支持吗？
现在虽然可以用Navigator的extras来搞，但还是链式调用就断了

**Comment by kymjs** [comment]
`1.1.1-rc2`已经支持，具体文档参考文章最底部：[https://therouter.cn/docs/2022/09/05/01](https://therouter.cn/docs/2022/09/05/01)

**Comment by goIntoAction** [comment]
@kymjs 发现 https://therouter.cn/docs/2022/08/27/01里面（底部）@Singleton是加载static方法上面的，但其实demo里面是加在interface上面，这个注解的声明target是class，是不是文档错了？

**Comment by kymjs** [comment]
> @kymjs 发现 https://therouter.cn/docs/2022/08/27/01 里面（底部） Singleton是加在static方法上面的，但其实demo里面是加在interface上面，这个注解的声明target是class，是不是文档错了？

是的，已改
