### ISSUE TITLE
修改Activity名称后，routeMap.json文件会重复生成

### ISSUE THREAD

**Issue by kylechandev** [HuolalaTech/hll-wp-therouter-android#141]
一个线上版本用户反馈的问题，发现是修改 Activity 名称后，routeMap.json 文件会重复生成，一个原来的旧的，和一个新的，没有进行替换。

它们的 path 都是一样的，只是 className 变了，因为Activity的名称修改了的嘛。

这时候如果再使用 TheRouter 去启动这个 path，会导致识别到原来的旧的，导致应用闪退，报 ActivityNotFoundException。

使用版本：1.2.2-rc5，AGP 8.2.1

希望可以尽快修复，感谢！

**Comment by kymjs** [comment]
看文档  https://therouter.cn/docs/2022/08/28/01
