### ISSUE TITLE
1.2.2-rc6 和Hilt冲突

### ISSUE THREAD

**Issue by MattFirefly** [HuolalaTech/hll-wp-therouter-android#146]
<img width="1099" alt="image" src="https://github.com/HuolalaTech/hll-wp-therouter-android/assets/8357627/882048f6-b431-4045-957d-b60e4e8bc93e">
当增加了@AndroidEntryPoint注解后会生成一个   "path": "",
<img width="572" alt="image" src="https://github.com/HuolalaTech/hll-wp-therouter-android/assets/8357627/b804b281-f1e4-4658-a315-8c422ebbff25">

<img width="495" alt="image" src="https://github.com/HuolalaTech/hll-wp-therouter-android/assets/8357627/27df0e0c-39ec-4749-a8ed-8811cea6d66c">
没有的着正常生成

<img width="555" alt="image" src="https://github.com/HuolalaTech/hll-wp-therouter-android/assets/8357627/cb4a4455-1c70-4e80-bf1f-6a13f3689c3a">

**Comment by kymjs** [comment]
KSP解析问题，暂不影响使用，下个rc版本修复

**Comment by kymjs** [comment]
已修复

https://github.com/HuolalaTech/hll-wp-therouter-android/releases/tag/1.2.2-rc7
