### ISSUE TITLE
TheRouter插件会导致 AndroidStudio 卡死

### ISSUE THREAD

**Issue by JamesGZM** [HuolalaTech/hll-wp-therouter-android#147]
MBP M1版本 Sonoma 14.1 (23B74)

Android Studio Iguana | 2023.2.1

TheRouter插件版本1.2.6

JDK 17.0.9

[heapReport20240304-173907.txt](https://github.com/HuolalaTech/hll-wp-therouter-android/files/14479585/heapReport20240304-173907.txt)

[idea.log](https://github.com/HuolalaTech/hll-wp-therouter-android/files/14479587/idea.log)

**Comment by Lans** [comment]
+1

**Comment by hnlbxb2004** [comment]
+1

**Comment by kymjs** [comment]
1.2.8插件已修复    
https://plugins.jetbrains.com/plugin/20047-therouter/versions/stable/605232
