### ISSUE TITLE
interface com.qx.common.provider.IRoomService is interface, but do not have @ServiceProvider

### ISSUE THREAD

**Issue by Lans** [HuolalaTech/hll-wp-therouter-android#148]
## module:common->IRoomService ,
module:A->
```
@ServiceProvider(returnType = IRoomService::class)
fun provideRoomService(): IRoomService = object : IRoomService {
    override fun getRoomId(): String {
        return "provideRoomService"
    }
}


@ServiceProvider(returnType = IRoomService::class)
class RoomProvider : IRoomService {
    override fun getRoomId(): String {
        return "1111"
    }

}
```

module B 
```
 val iRoomService = TheRouter.get(IRoomService::class.java)
                val roomId = iRoomService?.getRoomId()
                println("roomId:${roomId}")
```
## module A、B   全都api(“:common”)

**Comment by kymjs** [comment]
检查一下有没有引入apt或ksp

**Comment by Lans** [comment]
没个都加了ksp


来自 MEIZU 20

-------- 原始邮件 --------
发件人：张涛 ***@***.***>
时间：2024年3月9日 11:05
收件人：HuolalaTech/hll-wp-therouter-android ***@***.***>
抄送：Lans ***@***.***>,Author ***@***.***>
主题：Re: [HuolalaTech/hll-wp-therouter-android] interface com.qx.common.provider.IRoomService is interface, but do not have @ServiceProvider (Issue #148)
