### ISSUE TITLE
Failed to delete some children. This might happen because a process has files open or has its working directory set in the target directory.

### ISSUE THREAD

**Issue by liuyaxi** [HuolalaTech/hll-wp-therouter-android#156]
clean项目的时候会报如下错误
![QQ截图20240326163437](https://github.com/HuolalaTech/hll-wp-therouter-android/assets/17871784/0822f96c-57c2-499d-95ee-231c7b1700ba)
直接运行的时候会报如下错误
![微信图片_20240326163153](https://github.com/HuolalaTech/hll-wp-therouter-android/assets/17871784/84ca8eb9-f531-4474-9f32-8c20d12d4193)

**Comment by liuyaxi** [comment]
buildscript {
    dependencies {
        classpath 'com.android.tools.build:gradle:7.4.2'
        classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.5.20'
        classpath 'com.tencent.vasdolly:plugin:3.0.6'
        classpath "cn.therouter:plugin:1.2.1"
        classpath 'com.huawei.agconnect:agcp:1.7.3.300'
        classpath 'com.github.qq549631030:android-junk-code:1.1.2'
        classpath 'io.github.FlyJingFish.AndroidAop:android-aop-plugin:1.4.2'
    }
}
plugins {
// id 'org.jetbrains.kotlin.android' version '1.8.0' apply false
    id 'com.google.devtools.ksp' version '1.8.0-1.0.9' apply false
}

gradle    7.5  
android 工具版本（最新稳定版）
![QQ截图20240326163700](https://github.com/HuolalaTech/hll-wp-therouter-android/assets/17871784/fe343edd-dc4a-4cdb-bd2b-8c477df5b146)

arouter = { module = "cn.therouter:router", version = "1.2.1" }
arouterCompiler = { module = "cn.therouter:apt", version = "1.2.1" }

**Comment by liuyaxi** [comment]
jdk版本是17

**Comment by kymjs** [comment]
两个解决办法：
1. jdk用11  
2. `jdk17`+`gradle8`的依赖方式
