### ISSUE TITLE
编译异常问题

### ISSUE THREAD

**Issue by fuchengxin** [HuolalaTech/hll-wp-therouter-android#158]
jdk17，gradle-8.4 经常遇到这种编译异常，然后clean的时候提示下图这个，TheRouterGetAllClasses这个文件下的classes.jar清不掉，然后需要手动去任务管理器关闭java.exe这个进程才能clean成功，请问是什么问题?
![image](https://github.com/HuolalaTech/hll-wp-therouter-android/assets/15795966/d0e586ba-9779-4f06-a762-470f9512f23b)

**Comment by fuchengxin** [comment]
补充build里面的classes.jar图 clean只剩这一个清不掉
![image](https://github.com/HuolalaTech/hll-wp-therouter-android/assets/15795966/3266dff7-86f2-4b63-af29-a54785ca07a8)

**Comment by fuchengxin** [comment]
补充therouter版本，cn.therouter:router:1.2.2

**Comment by liuyaxi** [comment]
我也遇到过了 楼主解决了么
![QQ截图20240328164754](https://github.com/HuolalaTech/hll-wp-therouter-android/assets/17871784/9f71f187-7d81-4aab-9816-c64c0d74749b)

**Comment by liuyaxi** [comment]
agp 8.0+
gradle 8.2
jdk 官网下载的17版本
每次运行的时候都会出现楼主的那种情况。出现这样的情况需要把任务管理器里面的java任务给手动结束掉
![微信截图_20240328175413](https://github.com/HuolalaTech/hll-wp-therouter-android/assets/17871784/faea9bb9-0155-41df-9042-a91ad65d3f09)
如果不结束 不管是clean  还是rebuild都会报错
![QQ截图20240328174425](https://github.com/HuolalaTech/hll-wp-therouter-android/assets/17871784/7b3a79ac-9298-4a47-a441-4e7f37cb879f)

**Comment by liuyaxi** [comment]
> agp 8.0+ gradle 8.2 jdk 官网下载的17版本 每次运行的时候都会出现楼主的那种情况。出现这样的情况需要把任务管理器里面的java任务给手动结束掉 ![微信截图_20240328175413](https://private-user-images.githubusercontent.com/17871784/317682500-faea9bb9-0155-41df-9042-a91ad65d3f09.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2MjA0MDEsIm5iZiI6MTcxMTYyMDEwMSwicGF0aCI6Ii8xNzg3MTc4NC8zMTc2ODI1MDAtZmFlYTliYjktMDE1NS00MWRmLTkwNDItYTkxYWQ2NWQzZjA5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI4VDEwMDE0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1MjI0YmJiYWVjNDBjYWYzMTM0YzE3NjhkNjZlNTJjYjIxNGU4YzBkODUzYTM4NWI2NDQzMDk5MjEzNjNkOGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Gx5ZNp6HBCX-1y5H9sgwFRlw-5qa9u6VKJss3Q2aUkY) 如果不结束 不管是clean 还是rebuild都会报错 ![QQ截图20240328174425](https://private-user-images.githubusercontent.com/17871784/317682811-7b3a79ac-9298-4a47-a441-4e7f37cb879f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2MjA0MDEsIm5iZiI6MTcxMTYyMDEwMSwicGF0aCI6Ii8xNzg3MTc4NC8zMTc2ODI4MTEtN2IzYTc5YWMtOTI5OC00YTQ3LWE0NDEtNGU3ZjM3Y2I4NzlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI4VDEwMDE0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxMzBlNWVkNGEzODFlNWU2MzkzM2U5YjQ2ZmJkNzRlNTY0NmM1OTQ4MGJhMTU4N2ZiNmI5YWY1OTc1MzNjMWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-thnjyZjBDchSxgjJs7svO6fABIKimFs4q2yicxL1AI)

therouter 版本都是最新版本

**Comment by kymjs** [comment]
windows系统兼容问题，可参考微信群内群友给出的解决方案
![image](https://github.com/HuolalaTech/hll-wp-therouter-android/assets/5780230/9b47b0ab-e1b3-47f1-9081-94432a4b1be7)

**Comment by df13954** [comment]
这个问题就算不接入路由框架也存在的，之前的as版本就存在这个问题，偶尔会发生目录删除不了，后来就写了一个bat文件一键杀Java进程就解决了。不过根据我多年经验，这个问题只会出现在win系统上面，Ubuntu，macOS上面从未出现过。
