### ISSUE TITLE
apg8.0+   jdk17     gradle  8.2   项目在clean 会报错

### ISSUE THREAD

**Issue by liuyaxi** [HuolalaTech/hll-wp-therouter-android#159]
![QQ截图20240328174425](https://github.com/HuolalaTech/hll-wp-therouter-android/assets/17871784/a08162f6-081f-4687-a793-8c2cc22a52e0)
结束任务管理器里面的java进程clean就不会出错

**Comment by kymjs** [comment]
windows系统兼容问题，可参考微信群内群友给出的解决方案

![image](https://github.com/HuolalaTech/hll-wp-therouter-android/assets/5780230/7d3ffc73-4afd-4b88-91f4-9a5f046a929a)

**Comment by kymjs** [comment]
#158
