### ISSUE TITLE
每次改完代码之后不管clean、rebuild还是运行项目，都会报错一次，再重复一次操作就又好了

### ISSUE THREAD

**Issue by jiqianwen** [HuolalaTech/hll-wp-therouter-android#160]
![QQ截图20240403111602](https://github.com/HuolalaTech/hll-wp-therouter-android/assets/26268908/28dfb247-6629-4ee7-9782-7064ed2e2189)

**Comment by liuyaxi** [comment]
兄弟解决了么

**Comment by kymjs** [comment]
#97
