### ISSUE TITLE
gradle-8.2   Android Studio Hedgehog | 2023.1.1 Patch 2  打包失败

### ISSUE THREAD

**Issue by oudidi** [HuolalaTech/hll-wp-therouter-android#163]
v\* What went wrong:
An exception occurred applying plugin request [id: 'therouter']
> Failed to apply plugin 'therouter'.
   > API 'android.registerTransform' is removed.
     
     For more information, see https://developer.android.com/studio/releases/gradle-plugin-api-updates#transform-api.
     To determine what is calling android.registerTransform, use -Pandroid.debug.obsoleteApi=true on the command line to display more information.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

**Comment by kymjs** [comment]
#121
