### ISSUE TITLE
为什么传递基本类型参数生成代码的时候会报错？传递其它类型就可以，比如String

### ISSUE THREAD

**Issue by darkSuperman** [HuolalaTech/hll-wp-therouter-android#171]
AActivity:
```
   @Autowired(name = "NeedCompress")
    var needCompress: Boolean = false
```

跳转:
```
 TheRouter.build(RouteUrl.AActivity)
        .withBoolean("NeedCompress", true)
        .navigation()
```

报错：
needCompress 在 AActivity中是 private 访问控制
 target.needCompress = variableName0;
![image](https://github.com/HuolalaTech/hll-wp-therouter-android/assets/23699296/b65c4e9b-376d-460c-8268-18ce09428ac8)

**Comment by kymjs** [comment]
https://therouter.cn/docs/2023/07/21/01
