### ISSUE TITLE
Android agp8.0 编译速度

### ISSUE THREAD

**Issue by Firefly822** [HuolalaTech/hll-wp-therouter-android#173]
1、Android agp8支持增量编译吗？
感觉每次编译都在therouter步骤卡一会
2、是否可以提供参数配置扫描的目录？
这样可以过滤一些jar包，提升编译速度

版本：
    id("com.android.application") version "8.2.2" apply false
    id("cn.therouter.agp8") version "1.2.2" apply false

**Comment by Crzy633** [comment]
我手上的项目，随便改动一行代码，就会执行一个后缀叫`TheRouterGetAllClasses`的task，它输出的jar文件变动，导致`dexBuilder`task的时间变得很长

**Comment by sunlunchang1994** [comment]
我也是  编译时间太长了

**Comment by sunlunchang1994** [comment]
我也是  编译时间太长了

**Comment by lxlfpeng** [comment]
AGP8.3.2引入这个库改一句代码编译从十多秒变成五十多秒了,太耗时了,放弃了

**Comment by SoulfulVoyage** [comment]
AGP8.3.2 只改动任意一行代码,不依赖这个项目编译只要10秒左右,依赖这个框架则编译需要50秒以上.大大拖慢了开发效率,放弃了.

**Comment by kymjs** [comment]
`1.2.3-rc1` 已解决  
https://github.com/HuolalaTech/hll-wp-therouter-android/releases/tag/v1.2.3-rc1
