### ISSUE TITLE
API 'android.registerTransform' is removed.

### ISSUE THREAD

**Issue by shine12321** [HuolalaTech/hll-wp-therouter-android#178]
AGP8.3， 提示
   An exception occurred applying plugin request [id: 'therouter']
> Failed to apply plugin 'therouter'.
   > API 'android.registerTransform' is removed.
   没有人有这个问题吗？

**Comment by shine12321** [comment]
需要改为： id 'cn.therouter.agp8' version '1.2.2' apply false

**Comment by kymjs** [comment]
https://therouter.cn/docs/2023/07/21/01
