### ISSUE TITLE
在AGP8.3.2 上引入该工程导致编译速度变得巨慢

### ISSUE THREAD

**Issue by SoulfulVoyage** [HuolalaTech/hll-wp-therouter-android#179]
cn.therouter.agp8版本为 1.2.2
只改动任意一行代码,不依赖这个项目编译只要10秒左右,依赖这个框架则编译需要50秒以上.大大拖慢了开发效率,有对应的解决方案吗?

**Comment by kymjs** [comment]
`1.2.3-rc1`   
已解决 https://github.com/HuolalaTech/hll-wp-therouter-android/releases/tag/v1.2.3-rc1
