### ISSUE TITLE
出现java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by goIntoAction** [HuolalaTech/hll-wp-therouter-android#18]
`09-23 15:47:51.013 26549 26549 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: La/ServiceProvider__TheRouter__1380433389;
09-23 15:47:51.013 26549 26549 E AndroidRuntime: 	at a.TheRouterServiceProvideInjecter.addFlowTask(Unknown Source:10)
09-23 15:47:51.013 26549 26549 E AndroidRuntime: 	at com.therouter.TheRouter.init(TheRouter.kt:64)
09-23 15:47:51.013 26549 26549 E AndroidRuntime: 	at com.therouter.InnerTheRouterTrojan.onCreate(TheRouterTrojan.kt:26)
09-23 15:47:51.013 26549 26549 E AndroidRuntime: 	at android.content.ContentProvider.attachInfo(ContentProvider.java:2413)
09-23 15:47:51.013 26549 26549 E AndroidRuntime: 	at android.content.ContentProvider.attachInfo(ContentProvider.java:2383)
09-23 15:47:51.013 26549 26549 E AndroidRuntime: 	at android.app.ActivityThread.installProvider(ActivityThread.java:7771)
09-23 15:47:51.013 26549 26549 E AndroidRuntime: 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:7288)
09-23 15:47:51.013 26549 26549 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7028)
09-23 15:47:51.013 26549 26549 E AndroidRuntime: 	at android.app.ActivityThread.access$1800(ActivityThread.java:254)
09-23 15:47:51.013 26549 26549 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2184)
09-23 15:47:51.013 26549 26549 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
09-23 15:47:51.013 26549 26549 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:233)
09-23 15:47:51.013 26549 26549 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:344)
09-23 15:47:51.013 26549 26549 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8212)
09-23 15:47:51.013 26549 26549 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-23 15:47:51.013 26549 26549 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
09-23 15:47:51.013 26549 26549 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)`

项目结构
app module
接口module
实现a module
实现b module

module a、module b都是对接口的实现。app引用了接口module，当编译flavor a的时候，app引用的是实现a，当编译flavor b的时候，app引用的是实现b。a、b中都有各有一个ServiceProvider方法，现在发现不管哪种flavor，都会将module a、module b生成的类加到TheRouterServiceProvideInjecter中，但最终这个类并不会被打包进去，导致NoClassDefFoundError。

**Comment by kymjs** [comment]
参考 #7

**Comment by goIntoAction** [comment]
@kymjs 
我本地就是clean后编译的，我们公司的Jenkins也是无缓存的，都不行
这个项目使用的是kapt
gradle版本 gradle-7.3.3-all.zip，  com.android.tools.build:gradle:7.2.2

**Comment by goIntoAction** [comment]
是否能将AddCodeVisitor中java/lang/Exception改成java/lang/Throwable临时解决一下？

**Comment by kymjs** [comment]
> 是否能将AddCodeVisitor中java/lang/Exception改成java/lang/Throwable临时解决一下？

使用 `1.1.1-rc3`
