### ISSUE TITLE
RouterMap__TheRouter__xx 内的ROUTERMAP字段疑问

### ISSUE THREAD

**Issue by Caij** [HuolalaTech/hll-wp-therouter-android#181]
目前看RouterMap__TheRouter__xx会生成一个ROUTERMAP字段的路由表JSON，看起来是没有用的，在比较大的工程中，这个字符串长度很大，浪费性能。 
另外RouterMap__TheRouter__xx这个类有keep注解，导致这个字段混淆阶段不会优化掉。

**Comment by kymjs** [comment]
有用的，记录了当前模块的所有路由信息。
静态字符串不会造成性能问题，编译后会记录着JVM常量池。
