### ISSUE TITLE
1.2.3-rc1版本无法编译

### ISSUE THREAD

**Issue by Firefly822** [HuolalaTech/hll-wp-therouter-android#186]
`    id("cn.therouter.agp8") version "1.2.3-rc1" apply false`

An exception occurred applying plugin request [id: 'com.android.application']
> Failed to apply plugin 'com.android.internal.application'.
   > Could not create an instance of type com.android.build.gradle.internal.dsl.ApplicationExtensionImpl$AgpDecorated.
      > Could not generate a decorated class for type ApplicationExtensionImpl$AgpDecorated.
         > Mismatch of count of formal and actual type arguments in constructor of com.android.build.api.dsl.CommonExtension: 6 formal argument(s) 5 actual argument(s)

gradle 版本：8.2.2

**Comment by kymjs** [comment]
更新`gradle`版本即可  
https://github.com/HuolalaTech/hll-wp-therouter-android/blob/dev/agp8-project/gradle/wrapper/gradle-wrapper.properties
