### ISSUE TITLE
使用appcompat 1.7.0版本会导致编译报错（空指针异常）

### ISSUE THREAD

**Issue by yang961226** [HuolalaTech/hll-wp-therouter-android#187]
在dexBuilderDebug阶段会出现空指针异常：
![f66ab3b25dc5dea2bd097a5470625d6b](https://github.com/user-attachments/assets/3bbcffa2-f194-479f-823e-fbccb75de811)

发生错误的方法是com.android.build.gradle.internal.dexing.DexWorkAction

**Comment by kymjs** [comment]
Gradle版本问题，请参考demo工程配置

**Comment by 121104115wyb** [comment]
同样的问题，搞了很久，都没解决，最后决定还使用appcompat 1.6.1
