### ISSUE TITLE
并发情况下 ConcurrentModificationException

### ISSUE THREAD

**Issue by whoislxy** [HuolalaTech/hll-wp-therouter-android#188]
![截图 2024-07-30 10-49-39](https://github.com/user-attachments/assets/f341cc17-3b81-4a0d-ae09-a6f34b4b4e2a)

并发情况下报ConcurrentModificationException

**Comment by whoislxy** [comment]
![1722307944301](https://github.com/user-attachments/assets/7a749d27-8996-4d21-b4bb-2eb1b3a4c77e)

**Comment by kymjs** [comment]
`1.2.3-rc2`修复
