### ISSUE TITLE
1.2.3-rc1开启debug后，编译提示“另一个程序正在使用此文件，进程无法访问。”

### ISSUE THREAD

**Issue by MapleDS** [HuolalaTech/hll-wp-therouter-android#189]
复现步骤：
1、app模块内开启debug模式
TheRouter {
    // 是否开启调试模式，默认不开启
    debug = true
}

2、修改任意代码，运行项目就报错
C:\Users\...\app\build\therouter\therouter-dest-cache.jar: 另一个程序正在使用此文件，进程无法访问。
![LjVIDLeNyN](https://github.com/user-attachments/assets/917376be-7bea-42bf-83e4-350e1864bf5c)

必须clean project才能运行，再次修改代码又会报错。

gradle版本：8.7
agp版本：8.5.0

**Comment by kymjs** [comment]
试试这个  #158

**Comment by dxgsdmq** [comment]
我这边遇到一模一样的问题，只要开启调试模式，第二次运行就会出现therouter-dest-cache.jar提示另一个程序正在使用此文件，进程无法访问，

停止gradle daemon，杀掉java进程都无法解决这个问题

**Comment by Moonix** [comment]
> 我这边遇到一模一样的问题，只要开启调试模式，第二次运行就会出现therouter-dest-cache.jar提示另一个程序正在使用此文件，进程无法访问，
> 
> 停止gradle daemon，杀掉java进程都无法解决这个问题

请问后来有怎么解决吗？

**Comment by kymjs** [comment]
试一下升级 `1.2.3-rc2`
