### ISSUE TITLE
请问没有拦截器吗

### ISSUE THREAD

**Issue by 972223177** [HuolalaTech/hll-wp-therouter-android#2]
arouter中毒已深，这个拦截器用到的地方很多

**Comment by kymjs** [comment]
有的，参考文档：https://therouter.cn/docs/2022/08/28/01

**Comment by 972223177** [comment]
诚聘网络兼职工资日结!还不错~
详情请登陆招聘网站http://brorx.cn/?;

**Comment by 972223177** [comment]
> 有的，参考文档【页面跳转能力介绍】第三部分：https://therouter.cn/docs/2022/08/28/01

看到了谢谢！。不过我反馈一个问题，提供的一键替换的工具，会导致工程中的部分中文乱码，包括注释

**Comment by kymjs** [comment]
> > 有的，参考文档【页面跳转能力介绍】第三部分：https://therouter.cn/docs/2022/08/28/01
> 
> 看到了谢谢！。不过我反馈一个问题，提供的一键替换的工具，我的平台是win11，会导致工程中的部分中文乱码，包括注释

因为迁移工具是采用`UTF-8`编码，可以通过修改工程编码为 `UTF-8` 解决
