### ISSUE TITLE
关于功能 `导出路由文档` 的疑问

### ISSUE THREAD

**Issue by nichbar** [HuolalaTech/hll-wp-therouter-android#202]
你好

这边正在尝试从 ARouter 迁移到 TheRouter 

在文档说明的比较部分有提及到 `导出路由文档`，但是实际运行时只找到了输出的路由表 `routeMap.json`。 简单翻阅 `TheRouterTransform` 类，也没有找到导出路由文档的相关代码，请问要怎么才能导出类似 ARouter 风格的路由文档呢？

-------

以下是 ARouter 路由文档的示例

```json
{
    "activity": [
        {
            "group": "activity",
            "path": "/activity/item_detail",
            "description": "商品详情页",
            "className": "a.b.c.ItemDetailActivity",
            "type": "activity",
            "mark": -2147483648,
            "params": [
                {
                    "key": "id",
                    "type": "string",
                    "description": "商品 id",
                    "required": true
                }
            ]
        }
    ]
}
```

**Comment by kymjs** [comment]
TheRouter的文档就是json格式的。这么做的目的是支持打包机上，在构建过程中自定义打包过程做安全性检查和数据导出。

**Comment by nichbar** [comment]
是否可以这样理解，现在 TheRouter `导出路由文档` 功能指的就是导出 `routeMap.json` 文件，如果想要导出更详细的由 `@AutoWired` 修饰的变量需要使用方自行实现？

**Comment by kymjs** [comment]
是的，@AutoWired 修饰的变量后续新版本也会加入到json内
