### ISSUE TITLE
gradle 8.6编译出错

### ISSUE THREAD

**Issue by sanyouyugan** [HuolalaTech/hll-wp-therouter-android#204]
- Task `:app:debugTheRouterGetAllClasses` of type `com.therouter.plugin.agp8.TheRouterGetAllClassesTask`: invocation of 'Task.project' at execution time is unsupported.

**Comment by kymjs** [comment]
试一下 `1.2.3-rc2`

**Comment by kymjs** [comment]
`1.2.3-rc5`已修复
