### ISSUE TITLE
gradle升级到8.0.1集成1.2.2版本报错

### ISSUE THREAD

**Issue by hechaohua** [HuolalaTech/hll-wp-therouter-android#205]
我在app模块的build.gradle中添加 id 'cn.therouter.agp8' version '1.2.2' apply false，然后出现如下报错：
plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'cn.therouter.agp8' version '1.2.2' apply false
    id 'com.localazy.gradle'
    id 'kotlin-parcelize'
    id 'kotlin-kapt'//使用kapt依赖rxhttp-compiler，需要导入kapt插件
    // 应用 com.sensorsdata.analytics.android 插件
    // Add the Performance Monitoring Gradle plugin
    id 'com.google.firebase.firebase-perf'
    // id 'com.sensorsdata.analytics.android'
    id 'com.google.firebase.crashlytics'
    id 'com.google.gms.google-services'
}

A problem occurred configuring project ':app'.
> Could not resolve all files for configuration ':app:classpath'.
   > Could not find com.android.tools.build:gradle-api:8.0.1.
     Searched in the following locations:
       - https://plugins.gradle.org/m2/com/android/tools/build/gradle-api/8.0.1/gradle-api-8.0.1.pom
     If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
     Required by:
         project :app > cn.therouter.agp8:cn.therouter.agp8.gradle.plugin:1.2.2

**Comment by kymjs** [comment]
参考项目demo配置agp8
