### ISSUE TITLE
context 空指针

### ISSUE THREAD

**Issue by hust-twj** [HuolalaTech/hll-wp-therouter-android#208]
我们 APP 跳转的时候，有的场景没有传入 context 参数。

理论上 getApplicationContext() 通过 ContentProvider 初始化后赋值，应该不为 null，但是线上还是上报了少量的空指针。
线上也打印了日志， getApplicationContext() 确实为 null。

目前我的解决方案：
1. 路由跳转的时候尽量都带上 context
2. TheRouter 初始化的时候 检查 getApplicationContext() 是不是为null，为 null 则调用 setContext() 。

不过，建议底层的 nagavitor() 方法还是应该兜个底，或者 为 null 的时候直接抛异常，排查问题也会更加方便。

![image](https://github.com/user-attachments/assets/090edcdc-1235-40ba-9b03-387433a4e417)

![image](https://github.com/user-attachments/assets/d57e61e4-309d-4e5b-95dd-3863c63486b0)

![image](https://github.com/user-attachments/assets/4a5effde-6022-4843-b814-72842b4e4093)

**Comment by kymjs** [comment]
多进程的情况吧，子进程需要手动`setContext()`

**Comment by kymjs** [comment]
多进程的情况吧，子进程需要手动`setContext()`

**Comment by kymjs** [comment]
`1.2.3-rc5`加了逻辑判断，但只能保证`release`环境不崩溃，`debug`环境主动抛异常。为空的情况应该还是系统回收了，需要考虑一下怎么避免。
