### ISSUE TITLE
为啥不支持所有所有的Service实现类？

### ISSUE THREAD

**Issue by cocpublic** [HuolalaTech/hll-wp-therouter-android#21]
类似于这种
TheRouter.get(IUserService::class.java)?.getUserInfo()

**Comment by kymjs** [comment]
不太理解，详细描述一下？

**Comment by cocpublic** [comment]
> 不太理解，详细描述一下？

类似与WMRouter的  List<Class<IService>> classes = Router.getAllServiceClasses(IService.class);
有个比较典型的使用场景就是用于分发一些生命周期啥，比如账号 状态发生变化、退出账号啥的，需要将事件分发到所有注册了 IAccoutLifeCycle的模块里面去

**Comment by kymjs** [comment]
> > 不太理解，详细描述一下？
> 
> 类似与WMRouter的 List<Class> classes = Router.getAllServiceClasses(IService.class); 有个比较典型的使用场景就是用于分发一些生命周期啥，比如账号 状态发生变化、退出账号啥的，需要将事件分发到所有注册了 IAccoutLifeCycle的模块里面去

类似这种推荐用 `ActionManager`

**Comment by cocpublic** [comment]
> > > 不太理解，详细描述一下？
> > 
> > 
> > 类似与WMRouter的 List classes = Router.getAllServiceClasses(IService.class); 有个比较典型的使用场景就是用于分发一些生命周期啥，比如账号 状态发生变化、退出账号啥的，需要将事件分发到所有注册了 IAccoutLifeCycle的模块里面去
> 
> 类似这种推荐用 `ActionManager` https://therouter.cn/docs/2022/08/25/01

个人感觉action其实是一种弱化的service，返回值也只有boolean，相关流程限定在了ActionManner的框架内，没有自定Service灵活
