### ISSUE TITLE
关于TheRouter Service 下获取接口实现类产生的二义性

### ISSUE THREAD

**Issue by zhixiangfz** [HuolalaTech/hll-wp-therouter-android#213]
争议点：Service
事故起因：我们有多个业务块的SDK，A，B，C，D，A和B 实现了公用接口InF，当我使用InF去获取它的实现类，这时候不知道是使用A还是B。这样就产生了二义性。
诉求：
在阿里的ARouter中通过URI的方式路由到目标service，而TheRouter是以接口作为Key的形式获取目标实现类，之前的设计是因为什么原因不使用类似ARouter以URI的地址作为Key来获取目标接口的实现类？不太明白，能描述下吗
期望：
下个版本有支持的计划？感谢~

richsjeson
2024/11/20

**Comment by kymjs** [comment]
#122   参考文档1.3注意事项

**Comment by zhixiangfz** [comment]
所以我这里是应该采用这种写法，找到A？
比如A key:1
B key:2
C key:3
那么我的做法应该是
TheRouter.get(IF.class."1");然后我这时候可以找到A？
TheRouter.get(IF.class,"2")然后我这时候可以找到B？
