### ISSUE TITLE
多个实现类实现某个接口后产生的二义性

### ISSUE THREAD

**Issue by zhixiangfz** [HuolalaTech/hll-wp-therouter-android#214]
争议点：Service
事故起因：我们有多个业务块的SDK，A，B，C，D，A和B 实现了公用接口InF，当我使用InF去获取它的实现类，这时候不知道是使用A还是B。这样就产生了二义性。

按照你刚才给的例子来讲是否是以下的做法：

比如A key:1
B key:2
C key:3
那么我的做法应该是
TheRouter.get(IF.class."1");然后我这时候可以找到A？
TheRouter.get(IF.class,"2")然后我这时候可以找到B？

**Comment by kymjs** [comment]
#122
