### ISSUE TITLE
能否将功能进行一下拆分？

### ISSUE THREAD

**Issue by gittosuperfly** [HuolalaTech/hll-wp-therouter-android#27]
TheRouter很好用，但是功能感觉略有复杂。来看看它的功能：
1. 页面导航跳转能力
2. 跨模块依赖注入能力
3. 单模块自动初始化能力 
4. 动态化能力

作为一个Router，它的核心能力应该是1，最多再涉及一下2。而3和4，已经可以拆分出来作为一个独立的框架来使用了。

在我的两个项目中，A项目使用了router相关能力以及初始化能力，而2项目只需要它的初始化能力（因为我觉得蛮好用的），却要引入整个库及插件。

所以有没有考虑拆一下？

**Comment by kymjs** [comment]
比较难，其实最早也有这个想法，但是看一下实现就知道放弃的原因了。单模块初始化也是依赖编译时`APT`生成加上`Gradle Task`做循环依赖检查，这两块都放在一起的，如果单独拆开不仅编译会走两遍逻辑，时间加长，并且初始化时的逻辑也会需要区分路由表初始化前跟初始化后的状态，原本可以简单的实现就因为拆分反倒变复杂这肯定不是好的解决方案。
