### ISSUE TITLE
是否有计划支持AGP8.0?

### ISSUE THREAD

**Issue by galaxybruce** [HuolalaTech/hll-wp-therouter-android#28]
是否有计划支持AGP8.0?

**Comment by kymjs** [comment]
代码层面目前已兼容，详细进度可关注apg8分支。  
但由于`AGP8`现在都还是`alpha6`的版本，不确定将来是否还会发生`API`变动，直到`AGP8`退出正式版，我们才会发布对应`TheRouter`插件版本。

**Comment by kymjs** [comment]
link to  #22
