### ISSUE TITLE
项目从 ARouter 迁移 TheRouter 时通过 Bundle 传递的参数不能正确获取 value

### ISSUE THREAD

**Issue by yorkshenpolestar** [HuolalaTech/hll-wp-therouter-android#29]
项目从 ARouter 迁移 TheRouter 时通过 Bundle 传递的参数不能正确获取 value

# Example code

`NavigatorTestActivity`

```
Bundle bundle = new Bundle();
bundle.putInt("test_int_value", 1);

TheRouter.build(HomePathIndex.HOME)
    .with(bundle)
    .navigation();
```
    
`NavigatorTargetActivity`

```
Bundle bundle = getIntent().getExtras();
int intValueFromBundle = bundle.getInt("test_int_value", 0);

final TextView textView1 = findViewById(R.id.textview1);
textView1.setText("接收int值传递：integer2=" + intValueFromBundle);
```

## Expected Result

`integer2=1`

Bundle 结构是下面这种

![image](https://user-images.githubusercontent.com/18043540/199273498-9d48c858-a40d-420b-8393-0aaaa0e88409.png)

## Actual Result:

`integer2=0`

   
![image](https://user-images.githubusercontent.com/18043540/199272185-39e50908-6fec-4281-bd0e-86bb01c4ea07.png)

# Question

看起来与 ARouter 传递 Bundle 之后获取 Bundle 参数的方式不一致，不是能很平滑的迁移到 `TheRouter`. 

之前旧项目使用 `ARouter` 时都是使用的 

```
 ARouter.getInstance().build(path).with(bundle)
                .navigation(activity, requestCode)
```
传递参数，然后在对应页面使用  `intent.extras?.getBoolean(KEY_WEB_VIEW_CLOSE_MODE, false)` 这种方式获取参数，如果迁移到 `TheRouter` 之后必须使用 `@Autowired` 方式获取参数改动工作量会比较大。

我看了下源码：

```
fun with(value: Bundle?): Navigator = withBundle(KEY_BUNDLE, value)
```

我可以通过下面的方式获取传递的值

```
Bundle bundle = getIntent().getBundleExtra("therouter_bundle");
int intValueFromBundle = bundle.getInt("test_int_value", 0);
```

但是写法怪怪的，和以前用 `ARouter` 的写法也不兼容，是我写法有问题吗？或者有什么好的能够平滑迁移的建议？

**Comment by kymjs** [comment]
```
TheRouter.build("")
	.fillParams { bundle ->
	    bundle.putAll(yourBundle)
	}.navigation()
```

**Comment by yorkshenpolestar** [comment]
谢谢

**Comment by yorkshenpolestar** [comment]
![image](https://user-images.githubusercontent.com/18043540/199404759-60476086-30e2-4475-bd1a-989b3856f067.png)

一个简单的解决方法，遇到的可以参考一下
