### ISSUE TITLE
作者你好，提一个关于ActionInterceptor的问题

### ISSUE THREAD

**Issue by ljphawk** [HuolalaTech/hll-wp-therouter-android#30]
最近在使用TheRouter，功能非常强大，但在贴合业务场景时，我感觉addActionInterceptor的功能完全可以代替掉EventBus这种事件通知。
但是实际使用的话我觉得是否可以改进一下，比如我一个页面有多个事件通知，这些通知没有优先级，只是普通事件，处理业务逻辑。我要写多个TheRouter.addActionInterceptor(action,object:ActionInterceptor)，页面销毁的时候我想removeAction，结果发现要把object:的对象单独抽出来才能进行remove;
但如果我每次写的时候我都把ActionInterceptor参数写成this，并实现handle方法的话，在handler中统一处理action事件，我感觉代码可能更集中一些，不会太分散，但现在handler方法中少一个action字段，我并不能知道这是哪个action来的，能否在handler中增加上action参数？

**Comment by ljphawk** [comment]
既然这个能作为新功能，那我能不能再提一个需求，removeAction的时候我只传一个参数。
有两种情况哈，一种情况是只传actionName，清空源码中actionHandleMap对应key的list对象数据；
第二种是只传一个ActionInterceptor对象，remove源码中actionHandleMap中value有此对象的数据；

**Comment by kymjs** [comment]
可使用`1.1.2-rc1`版本。  

* 改动1：`TheRouter`类提供了两个API：

```kotlin
/**
 * 移除所有action对应的拦截器，如果action有多个拦截器，则都会被移除
 */
TheRouter.removeAllInterceptorForKey(action: String?)

/**
 * 移除所有指定拦截器，如果有多个action共用同一个拦截器，则都会被移除
 */
TheRouter. removeAllInterceptorForValue(interceptor: ActionInterceptor?)
```

* 改动2：`ActionInterceptor`类新增如下重载方法，其中`navigator.simpleUrl`即为`action` 

```kotlin
@CallSuper
open fun handle(context: Context, navigator: Navigator): Boolean
```

**Comment by ljphawk** [comment]
谢谢大佬，你太效率了！
