### ISSUE TITLE
按文档集成后，调用跳转方法。没反应。

### ISSUE THREAD

**Issue by 287138531** [HuolalaTech/hll-wp-therouter-android#31]
看了下生成的路由表是空的，不太明白是否有问题。
大佬能建个qq群吗？微信邀请二维码已经过期

18:38:27.111  D  TheRouter init start!
18:38:27.111  D  TheRouter.init() method do @FlowTask before task
18:38:27.113  D  TheRouter.init() method do @FlowTask init
18:38:27.113  D  TheRouter.init() method do @FlowTask schedule
18:38:27.114  D  TheRouter init finish!
18:38:27.114  D  will be add route map from： initDefaultRouteMap()
18:38:27.114  D  TheRouter auto init in Application
18:38:27.116  D  will be add route map from assets: []
18:38:27.193  D  begin navigate login_router_LoginActivity

**Comment by ljphawk** [comment]
我给你解答一下，你module的gradle文件中也要有 kapt

**Comment by kymjs** [comment]
官网有微信群入口   
https://therouter.cn/docs/2022/08/24/01

**Comment by 287138531** [comment]
> 官网有微信群入口 https://therouter.cn/docs/2022/08/24/01

二维码过期了
