### ISSUE TITLE
目标页面已经添加Route注解，生成的routeMap.json为空，无法跳转。

### ISSUE THREAD

**Issue by JasonMiller2110** [HuolalaTech/hll-wp-therouter-android#34]
目标页面已经添加Route注解，生成的routeMap.json为空，无法跳转。除非手动在routeMap.json中添加路由信息，才能跳转，但是携带的参数值通过 @Autowired无法获取到。genarated文件夹下也没有生成辅助类，求解，很急。无解就弃用了，社区无相关的blog可以借鉴。

**Comment by kymjs** [comment]
没有加注解处理器吧，可以官网加微信群寻求帮助。

所有模块的依赖都加上，不能只加最底层模块
```
kapt "cn.therouter:apt:1.1.1"
```
