### ISSUE TITLE
Support Gradle's configuration cache

### ISSUE THREAD

**Issue by Goooler** [HuolalaTech/hll-wp-therouter-android#35]
https://docs.gradle.org/7.5.1/userguide/configuration_cache.html

**Comment by kymjs** [comment]
org.gradle.unsafe.configuration-cache=true
org.gradle.configuration-cache=true
org.gradle.unsafe.configuration-cache-problems=warn
org.gradle.unsafe.configuration-cache.max-problems=5

**Comment by Goooler** [comment]
用到的项目开 `org.gradle.configuration-cache=true` 或者 `org.gradle.unsafe.configuration-cache=true` ，然后你们要在集成测试中开启 CC 标记位进行测试，可以参考 https://github.com/johnrengelman/shadow/pull/824

**Comment by Goooler** [comment]
添加 `org.gradle.unsafe.configuration-cache-problems=warn` 只是让 Gradle 统计 CC 的问题之后不要抛出异常，并没有真正解决问题，注意这只是一个 workaround.

**Comment by kymjs** [comment]
`1.2.3-rc1`   
已解决 https://github.com/HuolalaTech/hll-wp-therouter-android/releases/tag/v1.2.3-rc1
