### ISSUE TITLE
登录拦截

### ISSUE THREAD

**Issue by melancholyboy** [HuolalaTech/hll-wp-therouter-android#36]
在使用路由拦截器时，需要区分那些页面需要登录，登录成功跳转对应的页面；
使用Navigator.addRouterReplaceInterceptor拦截器进行拦截判断
使用Route注解中的params参数进行判断是否需要登录
由于params是传递的参数，感觉不优雅，有其他方式判断那些页面需要登录那些页面不需要登录吗？
之前使用ARouter路由框架，Route注解有一个extras参数，没有跟其他业务有依赖，所以可以使用判断

**Comment by kymjs** [comment]
我们是这样做的，你也可以通过配置json的方式
```
@Route(path = "xxx",params = {"needLogin", "true"})
public class MainActivity extends AppCompatActivity {
}

NavigatorKt.addRouterReplaceInterceptor(new RouterReplaceInterceptor() {
    @Nullable
    @Override
    public RouteItem replace(@Nullable RouteItem routeItem) {
        if (Boolean.valueOf(routeItem.getExtras().getString("needLogin"))) {
            return new loginRouterItem;
        }
        return routeItem;
    }
});
```

/assets/therouter/routeMap.json

```
  {
    "path": "xxxxx",
    "className": "xxxxx",
    "action": "",
    "description": "",
    "params": {
      "needLogin": "true"
    }
  }
```

**Comment by JamesGZM** [comment]
我是通过拼接/needLogin判断的
`@Route(path = "xxx/needLogin")
public class MainActivity extends AppCompatActivity {
}`
` addPathReplaceInterceptor(LoginInterceptor())`
`class LoginInterceptor : PathReplaceInterceptor() {

    override fun replace(path: String?): String? {
        if (path?.contains("/needLogin") == true) {
            if (!UserHelper.isLogin()) {
                //拦截操作，去调用登录
                return CommRouter.login
            }
        }
        return path
    }
}`
`routeMap.json`类似

**Comment by halzhang** [comment]
> 我们是这样做的，你也可以通过配置json的方式
> 
> ```
> @Route(path = "xxx",params = {"needLogin", "true"})
> public class MainActivity extends AppCompatActivity {
> }
> 
> NavigatorKt.addRouterReplaceInterceptor(new RouterReplaceInterceptor() {
>     @Nullable
>     @Override
>     public RouteItem replace(@Nullable RouteItem routeItem) {
>         if (Boolean.valueOf(routeItem.getExtras().getString("needLogin"))) {
>             return loginRouterItem;
>         }
>         return routeItem;
>     }
> });
> ```
> 
> 在 `/assets/therouter/routeMap.json`里面新增参数也可以达到等同于注解内添加的目的。
> 
> ```
>   {
>     "path": "xxxxx",
>     "className": "xxxxx",
>     "action": "",
>     "description": "",
>     "params": {
>       "needLogin": "true"
>     }
>   }
> ```

therouter 1.2.3版本，拿不到needLogin参数

```
@Route(path = "/detail/activity", params = ["needLogin", "true"])
class DetailActivity : AppCompatActivity() {

    companion object {
        @JvmStatic
        fun start(context: Context, message: String) {
            TheRouter.build("/detail/activity")
                .withString("message", message)
                .navigation(context)
        }
    }

class DemoApp : Application() {

    lateinit var loginRouteItem: RouteItem

    override fun onCreate() {
        super.onCreate()

        loginRouteItem = RouteItem(
            "/login/activity", "com.example.therouterdemo.ui.login.LoginActivity",
            "", ""
        )

        addRouterReplaceInterceptor(object : RouterReplaceInterceptor() {
            override fun replace(routeItem: RouteItem?): RouteItem? {
                if (routeItem?.getExtras()?.getString("needLogin").toBoolean()) {
                    if (!LoginUtils.isLogin()) {
                        return loginRouteItem
                    }
                }
                return routeItem
            }

        })
    }
}
```

是否在 
 ```
TheRouter.build("/detail/activity")
                .withString("message", message)
                .navigation(context) 
```

被覆盖了呢？

**Comment by kymjs** [comment]
@halzhang  因为缓存的问题，`1.2.4-rc6`修复了

**Comment by halzhang** [comment]
@kymjs 使用 1.2.4-rc6 还是一样的问题
