### ISSUE TITLE
FlowTask中TheRouter_application_oncreate执行时机问题

### ISSUE THREAD

**Issue by mtzqc** [HuolalaTech/hll-wp-therouter-android#38]
我理解的dependsOn= TheRouter_Before_Initialization 在Application.onCreate之前
dependsOn =  TheRouter_application_oncreate在SplashActivity.onCreate之前
 dependsOn = TheRouter_activity_splash应该在SplashActivity.onCreate之后
 但是事实TheRouter_application_oncreate的task一直在activity_splash之后,反而比TheRouter_activity_splash执行的时机更晚,
 原因是TheRouter在init时异步启动TheRouter_application_oncreate的task
![image](https://user-images.githubusercontent.com/29159362/205327236-bf1cdd48-709b-4fdb-886b-7206f300b5c0.png)
要想达到Application.onCreate之后SplashActivity.onCreate之前,只能在Application.onCreate中启动自定义任务
![image](https://user-images.githubusercontent.com/29159362/205327855-b93c72dd-1e50-4b9e-9fad-6d67d8bf6d2b.png)

**Comment by kymjs** [comment]
dependsOn只能保证task是在依赖任务之后执行，由于内部逻辑都是在异步线程操作，取决于线程切换，并不一定是立刻执行。  
放在异步的目的是为了防止订阅方在应用启动的时候做一些耗时操作，拖慢整个应用的启动速度。

详情请查阅官网文档：[业务节点订阅(自动初始化)能力介绍](https://therouter.cn/docs/2022/08/26/01) 
【`@FlowTask` 注解参数说明】部分
