### ISSUE TITLE
路由修改 添加 params = xxxx  ,路由表会生成多一条带params 的配置？要怎么操作才能清除，重新生成呢？

### ISSUE THREAD

**Issue by 287138531** [HuolalaTech/hll-wp-therouter-android#39]
我删除了路由重新编译才生成了新的路由

**Comment by kymjs** [comment]
是的，需要删除json内的路由项，详情参考官网文档：【3.3 路由表生成规则】  
[https://therouter.cn/docs/2022/09/04/01](https://therouter.cn/docs/2022/09/04/01)
