### ISSUE TITLE
引入插件后同步会提示警告信息

### ISSUE THREAD

**Issue by Chen-Xi-g** [HuolalaTech/hll-wp-therouter-android#47]
引入1.1.2版本，编译器执行同步操作会提示警告，日志如下
```
API 'android.registerTransform' is obsolete.
It will be removed in version 8.0 of the Android Gradle plugin.
The Transform API is removed to improve build performance. Projects that use the
Transform API force the Android Gradle plugin to use a less optimized flow for the
build that can result in large regressions in build times. It’s also difficult to
use the Transform API and combine it with other Gradle features; the replacement
APIs aim to make it easier to extend the build without introducing performance or
correctness issues.

There is no single replacement for the Transform API—there are new, targeted
APIs for each use case. All the replacement APIs are in the
`androidComponents {}` block.
For more information, see https://developer.android.com/studio/releases/gradle-plugin-api-updates#transform-api.
To determine what is calling android.registerTransform, use -Pandroid.debug.obsoleteApi=true on the command line to display more information.
Affected Modules: app
```
当我在`gradle.properties`添加`android.debug.obsoleteApi=true`后可以确定是引入插件`id 'therouter'`所引起的警告。
下面是警告信息和版本截图
![image](https://user-images.githubusercontent.com/37918545/211133410-f35d1a82-a6fc-4547-9dc2-ceeb42636be2.png)
![image](https://user-images.githubusercontent.com/37918545/211133414-2e0aa4bb-0fcf-4ceb-8e74-719e5b0f0847.png)
![image](https://user-images.githubusercontent.com/37918545/211133423-ed80ed98-dcf8-42e6-ad5f-341d16998961.png)

**Comment by Chen-Xi-g** [comment]
AGP 8.0.0 已发布，这将会是一个严重的问题

**Comment by kymjs** [comment]
参考官网文档：【从零接入 TheRouter】[https://therouter.cn/docs/2022/11/23/01](https://therouter.cn/docs/2022/11/23/01)

**Comment by Chen-Xi-g** [comment]
创建一个空项目，引入后也会提示此信息。
这是我的[Demo工程](https://github.com/Chen-Xi-g/TheRouterDemo)
![image](https://user-images.githubusercontent.com/37918545/211278401-f672d8de-9ffe-442c-a9a4-d6c68511c1ef.png)

**Comment by kymjs** [comment]
根着文档一步一步接，你接入的版本不对

**Comment by Chen-Xi-g** [comment]
TheRouter版本为1.1.2，这个问题不是版本问题吧，AGP 7.2 开始提高构建速度，通过 [Artifacts API](https://developer.android.com/reference/tools/gradle-api/7.3/com/android/build/api/artifact/Artifacts) 和 [Instrumentation API](https://developer.android.com/reference/tools/gradle-api/7.2/com/android/build/api/variant/Instrumentation) 取代 [Transform API](https://developer.android.com/reference/tools/gradle-api/7.0/com/android/build/api/transform/Transform)，后者会导致更长的构建时间并在 AGP 8.0 中消失。

TheRouterPlugin.groovy中使用了`android.registerTransform(therouterTransform);`，所以一直提示这个警告.

**Comment by kymjs** [comment]
#22 #28
