### ISSUE TITLE
如何在路由注册中声明需要登录，目前参数运行时全被抹掉

### ISSUE THREAD

**Issue by Gavinme** [HuolalaTech/hll-wp-therouter-android#48]
@Route(
    path = ROUTER_PATH_TEST_PAGE1,
    action = "needLogin",
)
class RouterActivity : AppCompatActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
      
    }
}

**Comment by kymjs** [comment]
参考官网文档：[https://therouter.cn/docs/2022/08/28/01](https://therouter.cn/docs/2022/08/28/01)    
【3.3 路由替换器】 部分
