### ISSUE TITLE
 @Autowired 子类无法获取该数据

### ISSUE THREAD

**Issue by Gavinme** [HuolalaTech/hll-wp-therouter-android#49]
@Autowired

**Comment by kymjs** [comment]
有具体实例吗，子类无法获取谁的数据

**Comment by Gavinme** [comment]
<img width="579" alt="image" src="https://user-images.githubusercontent.com/13794806/211436656-ab9b70ef-fdf8-4a66-884e-11439b300531.png">
<img width="792" alt="image" src="https://user-images.githubusercontent.com/13794806/211436698-d27daf14-d832-4afa-8745-ba31b7712b87.png">
XBusinessWebViewActivity 继承 AbsWebViewActivity，在 XBusinessWebViewActivity 无法获取到 url 的值

**Comment by kymjs** [comment]
可使用 `1.1.3-rc1`
