### ISSUE TITLE
请帮忙再把log里面的Trojan去掉。

### ISSUE THREAD

**Issue by goIntoAction** [HuolalaTech/hll-wp-therouter-android#50]
@kymjs 不好意思，我们做海外的，欧盟的机构用扫描工具扫到"Trojan"，请帮忙再修改一下，感谢

class InnerTheRouterContentProvider : ContentProvider() {
    override fun onCreate(): Boolean {
        applicationContext ?: let {
            applicationContext = context
        }
        if (theRouterUseAutoInit) {
            TheRouter.init(applicationContext)
            debug("Trojan", "TheRouter auto init in Application")
        }
        return true
    }
}

**Comment by kymjs** [comment]
可使用 `1.1.3-rc0`
