### ISSUE TITLE
父类@Autowared注解问题

### ISSUE THREAD

**Issue by l511809934** [HuolalaTech/hll-wp-therouter-android#54]
该框架对单Activity模式项目不太友好。建议可以封装一下fragment相关路由。包括fragment栈管理。跳转传参返回等。

**Comment by kymjs** [comment]
1. 单`fragment`是指单`Activity`吗？个人不推荐单`Activity`模式开发，低内存时的回收和生命周期管理极易错乱。如果使用，也建议使用`androidx`提供的`Navigation`和`FragmentFactory`来统一管理。
2. `Fragment(int)`也支持`@Autowared`的，在`Fragment`的`onViewCreated()`中调用`TheRouter.inject(this)`即可。

**Comment by l511809934** [comment]
父类fragment使用@Autowared接受公共字段接受不到。@kymjs

**Comment by l511809934** [comment]
父类fragment使用@Autowared接受公共字段接受不到。或者说子类获取不到父类定义的@Autowared字段，只能自己重新定义注解接受@kymjs

**Comment by kymjs** [comment]
参考 #49
