### ISSUE TITLE
不友好的功能吐槽

### ISSUE THREAD

**Issue by ZhengYiMin** [HuolalaTech/hll-wp-therouter-android#56]
fun with(value: Bundle?): Navigator = withBundle(KEY_BUNDLE, value)设置的Bundle应该像ARouter那样可以从intent获取Bundle中的参数，而不是先获取Bundle再从此Bundle中获取参数，希望可以改进。

**Comment by kymjs** [comment]
参考【需要手动修改的部分】，第四点   
https://therouter.cn/docs/2022/09/05/01

**Comment by ZhengYiMin** [comment]
已学习到,感谢!
