### ISSUE TITLE
kotlin使用@Autowired注解编译不通过

### ISSUE THREAD

**Issue by 20RenGY** [HuolalaTech/hll-wp-therouter-android#6]
@Autowired
    var uid: Int?=null

**Comment by kymjs** [comment]
Kotlin与Java互调时，默认会将类封装并生成getter/setter方法，并将原变量至为不可访问。  

有两种写法可以解决：

```
@JvmField
@Autowired
var uid: Int?=null
```

或者

```
@Autowired
lateinit var uid: Int
```

**Comment by 18633847058** [comment]
我也遇到了   不兼容的类型: NonExistentClass无法转换为Annotation @error.NonExistentClass()

**Comment by kymjs** [comment]
> NonExistentClass

参考`kapt`官方文档：[https://kotlinlang.org/docs/kapt.html#using-in-maven](https://kotlinlang.org/docs/kapt.html#using-in-maven)

```
kapt {
    correctErrorTypes true 
} 
```

**Comment by kymjs** [comment]
> 



> 我也遇到了 不兼容的类型: NonExistentClass无法转换为Annotation @error.NonExistentClass()

**Comment by 18633847058** [comment]
刚发现可能是你们迁移工具有点瑕疵，@Autowired阿里的引用包未删除导致的

**Comment by kymjs** [comment]
> 刚发现可能是你们迁移工具有点瑕疵，@Autowired阿里的引用包未删除导致的

是的，这个问题已经修复了，预计在国庆后发布新版本的迁移工具。

**Comment by darkSuperman** [comment]
> Kotlin与Java互调时，默认会将类封装并生成getter/setter方法，并将原变量至为不可访问。
> 
> 有两种写法可以解决：
> 
> ```
> @JvmField
> @Autowired
> var uid: Int?=null
> ```
> 
> 或者
> 
> ```
> @Autowired
> lateinit var uid: Int
> ```

```
@Autowired
lateinit var uid: Int

这种写法不行，会报错：'lateinit' modifier is not allowed on properties of primitive types
```
