### ISSUE TITLE
混淆打包出错

### ISSUE THREAD

**Issue by ZhengYiMin** [HuolalaTech/hll-wp-therouter-android#61]
Compilation failed to complete, position: Lcom/baidu/navcore/ui/b;onPause()V, origin: D:\AndroidStudioProjects\salehouse-kotlin-office\salehouse\build\intermediates\transforms\TheRouter\centaline\release\190.jar:com/baidu/navcore/ui/b.class

**Comment by ZhengYiMin** [comment]
package com.baidu.navcore.ui;

import android.app.Fragment;
import android.content.Context;
import android.content.Intent;
import android.content.res.Configuration;
import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.LinearLayout;
import com.baidu.navisdk.framework.interfaces.c;
import com.baidu.navisdk.framework.interfaces.l;
import com.baidu.navisdk.framework.interfaces.pronavi.m;
import com.growingio.android.sdk.autoburry.VdsAgent;
import com.growingio.android.sdk.instrumentation.Instrumented;
import com.sensorsdata.analytics.android.autotrack.aop.FragmentTrackHelper;
import com.sensorsdata.analytics.android.sdk.SensorsDataInstrumented;

@Instrumented
public class b extends Fragment {
  m a = null;
  
  public void onCreate(Bundle paramBundle) {
    super.onCreate(paramBundle);
    this.a = m1;
    m m1;
    if ((m1 = c.o().m()) != null) {
      m1
        
        .a(new a(this));
      this.a.onCreate((Context)getActivity());
    } 
  }
  
  public View onCreateView(LayoutInflater paramLayoutInflater, ViewGroup paramViewGroup, Bundle paramBundle) {
    super.onCreateView(paramLayoutInflater, paramViewGroup, paramBundle);
    m m1;
    if ((m1 = this.a) != null)
      return m1.a(getActivity(), paramBundle, (View)paramViewGroup); 
    return (View)new LinearLayout((Context)getActivity());
  }
  
  public void onStart() {
    super.onStart();
    m m1;
    if ((m1 = this.a) != null)
      super.onStart(); 
  }
  
  public void onConfigurationChanged(Configuration paramConfiguration) {
    super.onConfigurationChanged(paramConfiguration);
    m m1;
    if ((m1 = this.a) != null)
      super.onConfigurationChanged(paramConfiguration); 
  }
  
  public void onActivityResult(int paramInt1, int paramInt2, Intent paramIntent) {
    super.onActivityResult(paramInt1, paramInt2, paramIntent);
    m m1;
    if ((m1 = this.a) != null)
      super.onActivityResult(paramInt1, paramInt2, paramIntent); 
  }
  
  @SensorsDataInstrumented
  public void onResume() {
    VdsAgent.onFragmentResume(this);
    super.onResume();
    m m1;
    if ((m1 = this.a) != null)
      super.onResume(); 
    FragmentTrackHelper.trackFragmentResume(this);
  }
  
  @SensorsDataInstrumented
  public void onPause() {
    VdsAgent.onFragmentPause(this);
    super.onPause();
    m m1;
    if ((m1 = this.a) != null)
      super.onPause(); 
    FragmentTrackHelper.trackFragmentPause(this);
  }
  
  public void onStop() {
    super.onStop();
    m m1;
    if ((m1 = this.a) != null)
      super.onStop(); 
  }
  
  public void onDestroyView() {
    super.onDestroyView();
  }
  
  public void onDestroy() {
    super.onDestroy();
    m m1;
    if ((m1 = this.a) != null)
      super.onDestroy(); 
  }
  
  @SensorsDataInstrumented
  public void onHiddenChanged(boolean paramBoolean) {
    VdsAgent.onFragmentHiddenChanged(this, paramBoolean);
    super.onHiddenChanged(paramBoolean);
    FragmentTrackHelper.trackOnHiddenChanged(this, paramBoolean);
  }
  
  @SensorsDataInstrumented
  public void setUserVisibleHint(boolean paramBoolean) {
    VdsAgent.setFragmentUserVisibleHint(this, paramBoolean);
    super.setUserVisibleHint(paramBoolean);
    FragmentTrackHelper.trackFragmentSetUserVisibleHint(this, paramBoolean);
  }
  
  @SensorsDataInstrumented
  public void onViewCreated(View paramView, Bundle paramBundle) {
    super.onViewCreated(paramView, paramBundle);
    FragmentTrackHelper.onFragmentViewCreated(this, paramView, paramBundle);
  }
  
  class a implements l {
    a(b this$0) {}
    
    public void a() {
      com.baidu.navisdk.ui.routeguide.navicenter.b.b().a();
    }
  }
}

**Comment by kymjs** [comment]
看起来是百度sdk的问题，尝试把所有`com.therouter`都keep，看看是否还报错
