### ISSUE TITLE
API 'android.registerTransform' is removed.

### ISSUE THREAD

**Issue by TheMelody** [HuolalaTech/hll-wp-therouter-android#63]
![image](https://user-images.githubusercontent.com/9635441/227856791-cb02533c-e1ef-446c-807a-749c80b5ec09.png)

![image](https://user-images.githubusercontent.com/9635441/227857331-60efef30-1573-42d3-8eae-f5349ba8fbc2.png)

**Comment by kymjs** [comment]
参考  #22
