### ISSUE TITLE
插件建议

### ISSUE THREAD

**Issue by listengue** [HuolalaTech/hll-wp-therouter-android#65]
能不能兼容version catalog方式，用catalog方式引入插件报错。
Could not apply requested plugin [id: 'cn.therouter', version: '1.1.2'] as it does not provide a plugin with id 'cn.therouter'. This is caused by an incorrect plugin implementation. Please contact the plugin author(s).
> Plugin with id 'cn.therouter' not found.

**Comment by kymjs** [comment]
参考接入文档： https://therouter.cn/docs/2022/11/23/01
