### ISSUE TITLE
onNewIntent 里需要手动 调用TheRouter.inject(this) 么

### ISSUE THREAD

**Issue by w296365959** [HuolalaTech/hll-wp-therouter-android#66]
在onCreate 注册 TheRouter.inject(this)后，如果Activity页面 重走 onNewIntent ， @Autowired可以重新获取新Intent的数据，是否需要额外操作

**Comment by kymjs** [comment]
需要的

**Comment by w296365959** [comment]
同时还需要 setIntent 
`    
override fun onNewIntent(intent: Intent?) {
        super.onNewIntent(intent)
        setIntent(intent)
        TheRouter.inject(this) 
    }
`
