### ISSUE TITLE
不支持含有DynamicFeature的项目吗？

### ISSUE THREAD

**Issue by hutcwp** [HuolalaTech/hll-wp-therouter-android#67]

**Comment by kymjs** [comment]
支持的，使用上没有差异。需要在动态加载的模块被加载后手动调用一下路由表填充

**Comment by hutcwp** [comment]
我这边用1.1.2的版本尝试，在dynamicFeature模块的build中apply therouter插件，发现其并不会把dynamicFeature模块中定义的路由和service插入到TheRouterServiceProvideInjecter的initDefaultRouteMap，autowiredInject等方法中。原因是这个判断为false

**Comment by kymjs** [comment]
我理解错了，我以为是国内的插件化方案。
`dynamicFeature`可以使用 `1.1.3-rc4`，构建`dynamicFeature模块`时，需要将`app模块`的`build.gradle`中引入的插件去掉

**Comment by hutcwp** [comment]
看了您兼容dynamicFeature的修改c6081d1fbd40badae735c2bbc2aa3300a5c6aadb。但是感觉跟我遇到的场景不太一样。我这边是国外的项目需要用aab格式上googlePlay，项目中有的moudel用了DynamicFeature类型，但是该moudle不是动态下发的，另外打包的时候dynamicFeature也是跟随app模块一起打包的。不会像插件化那样单独去打插件包。所以我这边思考的方向是在打包的时候去遍历到App模块和所有dynamicfeature模块中的初始化类，然后再插桩到TheRouterServiceProvideInjecter中的初始化方法中去。

**Comment by kymjs** [comment]
插件就是做这件事的，用这种方式就可以

> 我理解错了，我以为是国内的插件化方案。 `dynamicFeature`可以使用 `1.1.3-rc4`，构建`dynamicFeature模块`时，需要将`app模块`的`build.gradle`中引入的插件去掉

**Comment by hutcwp** [comment]
> 插件就是做这件事的，用这种方式就可以
> 
> > 我理解错了，我以为是国内的插件化方案。 `dynamicFeature`可以使用 `1.1.3-rc4`，构建`dynamicFeature模块`时，需要将`app模块`的`build.gradle`中引入的插件去掉

app模块和dynamicFeature模块都有路由页面，需要同时在app模块和dynamicFeature模块的build.gradle中依赖插件transform才会遍历到各自moudle中的类和Jar。另外app模块和dynamicFeature模块是一起构建的，没办法做到构建dynamicFeature模块的时候把app模块的build.gradle中引入的插件去掉。

**Comment by kymjs** [comment]
你的`dynamicFeature`应该也会依赖`app`吧。
