### ISSUE TITLE
编译过程中出现大量警告，有办法去掉吗

### ISSUE THREAD

**Issue by linqip** [HuolalaTech/hll-wp-therouter-android#68]
nsforms/TheRouter/devEnv/release/98.jar: R8: Expected stack map table for method with non-linear control flow. In later version of R8, the method may be assumed not reachable.
WARNING:/Users/cn22-i570455-a/StudioProjects/catl-android/app/build/intermediates/transforms/TheRouter/devEnv/release/154.jar: R8: Expected stack map table for method with non-linear control flow. In later version of R8, the method may be assumed not reachable.
WARNING:/Users/cn22-i570455-a/StudioProjects/catl-android/app/build/intermediates/transforms/TheRouter/devEnv/release/154.jar: R8: Expected stack map table for method with non-linear control flow. In later version of R8, the method may be assumed not reachable.
WARNING:/Users/cn22-i570455-a/StudioProjects/catl-android/app/build/intermediates/transforms/TheRouter/devEnv/release/154.jar: R8: Expected stack map table for method with non-linear control flow. In later version of R8, the method may be assumed not reachable.

**Comment by kymjs** [comment]
请关闭R8

**Comment by linqip** [comment]
您的邮件已经收到了，我看到后会第一时间回复的。 谢谢 ！

**Comment by likfe** [comment]
The option 'android.enableR8' is deprecated.
It was removed in version 7.0 of the Android Gradle plugin.
Please remove it from `gradle.properties`.

**Comment by likfe** [comment]
> 请关闭R8

AGP7下，关闭R8无效了，还有其他方案吗？
