### ISSUE TITLE
升级as flamingo 后编译报错

### ISSUE THREAD

**Issue by 287138531** [HuolalaTech/hll-wp-therouter-android#69]
![{0L)%J% UNA(IY5SN{IA38C](https://user-images.githubusercontent.com/13412535/232374875-9c5893b8-443e-4102-9f26-fb939207bc72.png)
![59%Y5CZ~M~ `}HHFXV64TV](https://user-images.githubusercontent.com/13412535/232374880-b47bac2a-8b49-42a0-8c07-095a9243557f.png)

**Comment by goIntoAction** [comment]
我也碰到这个问题

**Comment by kymjs** [comment]
排查后，是由于`JDK`使用了`AS`自带的`jbr`造成的。   
修复办法：使用`openJDK`可解决

**Comment by winfirm** [comment]
@kymjs TheRouterAnnotationProcessor中输出java类的PrintStream能否指定为UTF-8格式？ WIN11换成OpenJDK11了，依然报编码问题。谢谢。

**Comment by melancholyboy** [comment]
同样遇到了该问题，升级了gradle和jdk gradle插件版本：7.1.2  jdk版本：17.0.5，jdk为openJdk
