### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: La/RouterMap__TheRouter__1361269576;

### ISSUE THREAD

**Issue by 20RenGY** [HuolalaTech/hll-wp-therouter-android#7]
java.lang.NoClassDefFoundError: Failed resolution of: La/RouterMap__TheRouter__1361269576;
        at a.TheRouterServiceProvideInjecter.initDefaultRouteMap(Unknown Source:0)
在release下启动直接报错

**Comment by kymjs** [comment]
如果是本地打包：需要clean一下
如果是jenkins：建议勾选清空工作空间

**Comment by kymjs** [comment]
可以使用 `1.1.1-rc3`   #18
