### ISSUE TITLE
耗时问题咨询

### ISSUE THREAD

**Issue by xiaxinqing** [HuolalaTech/hll-wp-therouter-android#76]
接入ARouter 发现 init方法非常耗时，TheRouter 存在这个问题吗？请大佬解惑

**Comment by kymjs** [comment]
ARouter 在路由表数量庞大、Group很多的情况下，性能会下降很多。
两个原因：
1. 因为他分组初始化，每个group都是懒加载的方式被logiccenter调用的，在首次跳转到目标Activity的时候会触发一次路由表加载
2. 是因为他的路由表初始化在主线程完成的，正常情况下其实没问题只会白屏一会，当路由表特别多的时候卡顿会比较明显。

TheRouter 没有路由分组概念，所有路由表都是启动时在异步加载的，对于没有初始化完就发生跳转的行为，是通过挂起的方式延迟跳转操作，在`demo`的`Application`里面有演示。
