### ISSUE TITLE
弱弱的问一句,有谁拉项目,跑不起来的吗

### ISSUE THREAD

**Issue by lydlovezjr** [HuolalaTech/hll-wp-therouter-android#8]
<img width="914" alt="微信截图_20220916095944" src="https://user-images.githubusercontent.com/19246347/190540201-e6a1c61e-66d7-4339-8565-76e6e763a230.png">

**Comment by kymjs** [comment]
查看官网文档第五项：【源码运行与调试】

**Comment by lydlovezjr** [comment]
app=true
business-base=true
business-a=true
business-b=true

git clone的项目不大行,最后下载的zip包解压的才可以了
