### ISSUE TITLE
agp8.0版本 with Bundle问题

### ISSUE THREAD

**Issue by cike978** [HuolalaTech/hll-wp-therouter-android#80]
arouter使用工具迁移到throuter中 代码 TheRouter.build(“/test”.with(intent.getExtras()).navigation(context); 和arouter有差异
arouter  .with(intent.getExtras()) 会将bundle中的key解析出来放到intent中，而therouter 是在intent中增加了一个 therouter_bundle 的key，两种方式不一致，建议处理一下或者工具不要转换，开发者自己处理；也可以在增加一个方法，保持与arouter的一致

**Comment by cike978** [comment]
``java

 public static void startChatActivity(Context context, Intent intent) {
        try {


//            TheRouter.build(RouterFactory.getRouterPath(RouterKeys.KEY_CHAT_CONVERSATION))
//                    .with(intent.getExtras()).navigation(context);
            TheRouter.build(RouterFactory.getRouterPath(RouterKeys.KEY_CHAT_CONVERSATION))
                    .fillParams(bundle -> {
                      bundle.putAll(intent.getExtras());
                        return null;
                    }).navigation(context);
``
可以这样处理，只是有点繁琐

**Comment by kymjs** [comment]
https://therouter.cn/docs/2022/09/05/01
