### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by Apeplan** [HuolalaTech/hll-wp-therouter-android#85]
Android Studio Flamingo | 2022.2.1
Build #AI-222.4459.24.2221.9862592, built on March 31, 2023
Runtime version: 17.0.6+0-17.0.6b802.4-9586694 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.6.6

![image](https://github.com/HuolalaTech/hll-wp-therouter-android/assets/6419795/3a15fc4d-f3b7-4599-b682-8333d0d8c892)
![image](https://github.com/HuolalaTech/hll-wp-therouter-android/assets/6419795/6272acf2-f5fa-4be6-8c77-97402223c1dd)

错误信息：
![image](https://github.com/HuolalaTech/hll-wp-therouter-android/assets/6419795/cbea3582-c0a9-489e-b7fa-b54c1361e23e)

**Comment by kymjs** [comment]
版本号不对

**Comment by Apeplan** [comment]
谁的版本号不对，Kotlin? ksp? router ？ 我看着教程搞的，报错后又看了两遍实在是没看出来，还请赐教：是哪个版本有问题？谢谢

**Comment by Apeplan** [comment]
好，我看又看了两遍文档，跟着文档搞的。有翻了下仓库代码，发现插件版本跟依赖库的是一致的，我跟着文档把插件设置成1.1.4-rc2或者1.2.0-beta2，但是依赖库的是1.1.1。现在都改成1.2.0-beta2可以了，谢谢
