### ISSUE TITLE
像Arouter这种Scheme要怎么实现呢

### ISSUE THREAD

**Issue by NeVaDaAAA** [HuolalaTech/hll-wp-therouter-android#9]
![image](https://user-images.githubusercontent.com/20659340/190551769-acbbf0d1-c559-46f3-9c4a-29fcf5c2e455.png)

**Comment by kymjs** [comment]
TheRouter支持`path`和页面`多对一`关系，所以不存在`ARouter`这种冲突的问题，可以按照Android正常的`scheme`逻辑跳转。
