### ISSUE TITLE
编译时一直警告下面这个，有办法解决吗

### ISSUE THREAD

**Issue by jkbwfi** [HuolalaTech/hll-wp-therouter-android#90]
WARNING:/___android/app/build/intermediates/transforms/TheRouter/release/372.jar: R8: Expected stack map table for method with non-linear control flow. In later version of R8, the method may be assumed not reachable.
WARNING:/___android/app/build/intermediates/transforms/TheRouter/release/372.jar: R8: Expected stack map table for method with non-linear control flow. In later version of R8, the method may be assumed not reachable.
WARNING:/___android/app/build/intermediates/transforms/TheRouter/release/372.jar: R8: Expected stack map table for method with non-linear control flow. In later version of R8, the method may be assumed not reachable.
WARNING:/___android/app/build/intermediates/transforms/TheRouter/release/372.jar: R8: Expected stack map table for method with non-linear control flow. In later version of R8, the method may be assumed not reachable.
WARNING:/___android/app/build/intermediates/transforms/TheRouter/release/372.jar: R8: Expected stack map table for method with non-linear control flow. In later version of R8, the method may be assumed not reachable.
WARNING:/___android/app/build/intermediates/transforms/TheRouter/release/372.jar: R8: Expected stack map table for method with non-linear control flow. In later version of R8, the method may be assumed not reachable.
WARNING:/___android/app/build/intermediates/transforms/TheRouter/release/372.jar: R8: Expected stack map table for method with non-linear control flow. In later version of R8, the method may be assumed not reachable.
WARNING:/___android/app/build/intermediates/transforms/TheRouter/release/372.jar: R8: Expected stack map table for method with non-linear control flow. In later version of R8, the method may be assumed not reachable.
WARNING:/___android/app/build/intermediates/transforms/TheRouter/release/372.jar: R8: Expected stack map table for method with non-linear control flow. In later version of R8, the method may be assumed not reachable.
WARNING:/___android/app/build/intermediates/transforms/TheRouter/release/372.jar: R8: Expected stack map table for method with non-linear control flow. In later version of R8, the method may be assumed not reachable.
WARNING:/___android/app/build/intermediates/transforms/TheRouter/release/372.jar: R8: Expected stack map table for method with non-linear control flow. In later version of R8, the method may be assumed not reachable.
WARNING:/___android/app/build/intermediates/transforms/TheRouter/release/372.jar: R8: Expected stack map table for method with non-linear control flow. In later version of R8, the method may be assumed not reachable.
WARNING:/___android/app/build/intermediates/transforms/TheRouter/release/372.jar: R8: Expected stack map table for method with non-linear control flow. In later version of R8, the method may be assumed not reachable.
WARNING:/___android/app/build/intermediates/transforms/TheRouter/release/372.jar: R8: Expected stack map table for method with non-linear control flow. In later version of R8, the method may be assumed not reachable.
WARNING:/___android/app/build/intermediates/transforms/TheRouter/release/372.jar: R8: Expected stack map table for method with non-linear control flow. In later version of R8, the method may be assumed not reachable.
WARNING:/___android/app/build/intermediates/transforms/TheRouter/release/372.jar: R8: Expected stack map table for method with non-linear control flow. In later version of R8, the method may be assumed not reachable.
WARNING:/___android/app/build/intermediates/transforms/TheRouter/release/372.jar: R8: Expected stack map table for method with non-linear control flow. In later version of R8, the method may be assumed not reachable.
WARNING:/___android/app/build/intermediates/transforms/TheRouter/release/372.jar: R8: Expected stack map table for method with non-linear control flow. In later version of R8, the method may be assumed not reachable.
WARNING:/___android/app/build/intermediates/transforms/TheRouter/release/372.jar: R8: Expected stack map table for method with non-linear control flow. In later version of R8, the method may be assumed not reachable.
WARNING:/___android/app/build/intermediates/transforms/TheRouter/release/372.jar: R8: Expected stack map table for method with non-linear control flow. In later version of R8, the method may be assumed not reachable.
WARNING:/___android/app

**Comment by s1h** [comment]
请问是怎么解决的？
