### ISSUE TITLE
关于kotlin 使用 @ServiceProvider编译报错

### ISSUE THREAD

**Issue by xiaowifi** [HuolalaTech/hll-wp-therouter-android#91]
你好，我将demo中的
![image](https://github.com/HuolalaTech/hll-wp-therouter-android/assets/18083634/0e50d1b6-7a5b-493e-8f95-622ff96e9d14)
拷贝到我们项目工程中，编译的时候依旧报错，我们gradle 版本为 gradle-7.5-all。
下面提供生成的错误的class：

public class ServiceProvider__TheRouter__1340536089 implements com.therouter.inject.Interceptor {

	public static final String TAG = "Created by kymjs, and APT Version is 1.1.3.";
	public static final String THEROUTER_APT_VERSION = "1.1.3";
	public static final String FLOW_TASK_JSON = "{}";

	public <T> T interception(Class<T> clazz, Object... params) {
		T obj = null;
		if (com.therouter.app.serviceprovider.IKotlinSerivce.class.class.equals(clazz) && params.length == 1
				&& params[0] instanceof {android.content.Context.class) {
			//type verification during compilation prevents the actual return type of the method from mismatching with the return type declared by the annotation
			com.therouter.app.serviceprovider.IKotlinSerivce.class returnType = com.therouter.app.serviceprovider.IKotlinServiceProviderKt.create(({android.content.Context.class) params[0]);
			obj = (T) returnType;
		} else {

        }
        return obj;
    }

	public static void addFlowTask(android.content.Context context, com.therouter.flow.Digraph digraph) {
	}
}

**Comment by kymjs** [comment]
https://therouter.cn/docs/2023/07/21/01
