### ISSUE TITLE
Flowtask 业务节点初始化无效

### ISSUE THREAD

**Issue by jokerrou** [HuolalaTech/hll-wp-therouter-android#92]
flowtask初始化失败，方式如下：
```
@FlowTask(taskName = "base_init_smartRefresh")
fun initSmartRefresh(context: Context){
    BaseAppHelper.initSmartRefreshLayoutHeaderAndFooter(context as Application)
}

```
尝试了所有的初始化节点跟方式  都不行
![image](https://github.com/HuolalaTech/hll-wp-therouter-android/assets/12645305/3391d0ff-35ff-42a0-85b0-5b9d5a17223f)

然后我换成在applicaiton的oncreate里面去初始化，成功了，按大佬说的flowTask也是在application的onCreate()里面去执行，那效果应该是一样的才对，所以我目前搞不懂是啥原因导致的

而且编译器打印的初始化任务 时有时无。。。这也不知道啥原因导致的

**Comment by kymjs** [comment]
请更新版本号至 `1.2.0-rc4` 后再次尝试

**Comment by jokerrou** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by hlovingness** [comment]
我的也不行 版本号是 1.2.0-rc6

**Comment by jokerrou** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
