### ISSUE TITLE
routeMap路由表不生成

### ISSUE THREAD

**Issue by jokerrou** [HuolalaTech/hll-wp-therouter-android#94]
版本：1.1.4-rc4
模块已添加ksp依赖
父类不包含泛型 
用ksp不能生成路由表 kapt可以

**Comment by kymjs** [comment]
https://therouter.cn/docs/2023/07/21/01

**Comment by jokerrou** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
