### ISSUE TITLE
【BUG反馈】依赖了最新版本,编译的时候容易出现 NestHost requires ASM7 

### ISSUE THREAD

**Issue by zhoujianli1016** [HuolalaTech/hll-wp-therouter-android#95]
![1ad98d82d4c98161ce41e1810f384b4](https://github.com/HuolalaTech/hll-wp-therouter-android/assets/22313845/5b18b753-0001-4eb4-bac3-8f4c2625c8e2)

**Comment by kymjs** [comment]
#93
