### ISSUE TITLE
不支持gradle8.0

### ISSUE THREAD

**Issue by workgithubly** [HuolalaTech/hll-wp-therouter-android#97]
<img width="835" alt="image" src="https://github.com/HuolalaTech/hll-wp-therouter-android/assets/6802893/46ffb625-4274-496e-b024-dac37ceb6cf7">
<img width="639" alt="image" src="https://github.com/HuolalaTech/hll-wp-therouter-android/assets/6802893/ae26b95c-9032-4c1a-8c4f-b71ef79af121">
<img width="570" alt="image" src="https://github.com/HuolalaTech/hll-wp-therouter-android/assets/6802893/c8b7a699-632a-488e-9e47-97d1d161d73c">

**Comment by workgithubly** [comment]
<img width="454" alt="image" src="https://github.com/HuolalaTech/hll-wp-therouter-android/assets/6802893/b2b124f2-961d-4ca4-9ce3-8596a8b782fa">

**Comment by cxjwmy** [comment]
AGP 都8.1.0 了，什么时候1.2.0能发正式版啊

**Comment by kymjs** [comment]
看官网文档

**Comment by kymjs** [comment]
> AGP 都8.1.0 了，什么时候1.2.0能发正式版啊

快了，已经发rc了

**Comment by wzgl5533** [comment]
我也遇到这个问题

**Comment by wzgl5533** [comment]
有没有解决办法

>

**Comment by kymjs** [comment]
https://therouter.cn/docs/2022/11/23/01

**Comment by wzgl5533** [comment]
> https://therouter.cn/docs/2022/11/23/01

我看了，就是在APP目录引入插件报错，我也不知道哪里有问题。therouterVersion = "1.2.0-rc1"
![image](https://github.com/HuolalaTech/hll-wp-therouter-android/assets/11958496/d7f563b5-0a4d-400a-a912-8adf443fc563)
![image](https://github.com/HuolalaTech/hll-wp-therouter-android/assets/11958496/61bee788-2e80-4f04-a4f5-2065ddffc064)

**Comment by kymjs** [comment]
`Gradle`版本号是多少

**Comment by wzgl5533** [comment]
> `Gradle`版本号是多少

gradleVersion = "8.1.1"

**Comment by kymjs** [comment]
把`第一步：接入classpath`再看一遍
