### ISSUE TITLE
内存无法被释放

### ISSUE THREAD

**Issue by l511809934** [HuolalaTech/hll-wp-therouter-android#98]
![image](https://github.com/HuolalaTech/hll-wp-therouter-android/assets/18045648/04a71e95-58d0-4046-85f5-6b40d1fc53fb)
如图所示pushHistory方法几乎会存所有的操作，导致内存被撑爆无法被释放。这里应该设计一个开关。默认不记录
 therouter_version = '1.1.3'

**Comment by kymjs** [comment]
下个版本修复
