### ISSUE TITLE
子Module无论怎样都生成不出来路由

### ISSUE THREAD

**Issue by mkk814** [HuolalaTech/hll-wp-therouter-android#99]
最新的1.1.4-rc8，

**Comment by mkk814** [comment]
这几条都满足 ：
plugin 加了吗？plugin 必须加且只能加在 app 模块里。
kapt加了吗？kapt不能只加最底层，所有用了注解的模块都要加。
router、plugin、kapt，三个依赖的版本号必须一致。
在这里查看JDK信息：Preferences-> Build Tools-> Gradle-> Gradle JDK。不能用AS自带的jdk，会有兼容问题。

**Comment by kymjs** [comment]
使用的是kapt还是ksp

**Comment by kymjs** [comment]
`1.2.0-rc4` 已修复
https://github.com/HuolalaTech/hll-wp-therouter-android/releases/tag/v1.2.0-rc4

**Comment by mkk814** [comment]
The Router支持频繁的利用 TheRouter.build(uiMainPath) .withSerializable(parameter, parameters).navigation()的形式频繁传递参数么  ；有没有刷新参数的机制的；
